import {q,f,m,p,type Both,type Bilingual} from './course-fix-builders';

export const FOUNDATION_QUESTIONS:Record<string,Record<number,Both>>={
 '4-1':{
  1:q(['哪项最能体现本课所说的 Agent 行动方式？','Which best illustrates agentic behavior in this lesson?'],[['根据工具结果选择下一步，执行后检查是否接近目标','Choose the next action from tool results, then check progress toward the goal'],['对每份输入执行相同的预设步骤和分支','Run the same predefined steps and branches for each input'],['在多轮对话中记住称呼并润色句子','Remember a name across chat turns and polish sentences']],['关键是围绕目标选择行动并检查结果；多轮聊天或接入工具本身不足以区分。','The distinction is goal-directed action selection and checking, not chat length or tool access alone.']),
  2:q(['观星社只授权读取两份公开资料并准备草稿。哪种分工符合这个边界？','The club authorizes reading two public sources and preparing a draft only. Which arrangement respects that scope?'],[['提取观察对象、核对来源并交付草稿','Extract observation targets, verify sources, and deliver a draft'],['完成草稿后自行挑选收件人发送','Choose recipients and send after drafting'],['资料不足时访问成员私人聊天补充','Read members’ private chats if sources are insufficient']],['这里检验授权范围；固定资料的提取也能由工作流完成，并非只有 Agent 能做。','This tests authorization. Extracting fixed sources can also be done by a workflow; it does not uniquely require an agent.']),
  3:q(['本课任务只允许出海报草稿。完成后建议“现在发布”，应该怎样处理？','The task allows a poster draft only. On completion, it suggests publishing. What next?'],[['核对内容、素材许可和受众，由负责人决定发布','Have the owner review content, permissions, and audience and decide on publication'],['只要没有个人信息，就自动发布','Publish automatically if no personal information appears'],['沿用上次海报的批准，发布这次新内容','Reuse approval for the previous poster to publish the new content']],['新内容与新受众需要对应的确认，去掉个人信息并不扩大原有权限。','New content and audience need applicable approval; removing personal data does not expand permission.']),
  4:q(['哪条目标最容易按约定检查是否完成？','Which goal provides the clearest completion check?'],[['依据两份指定天文资料，写活动提醒草稿，列三个对象及来源，不发送','Use two specified astronomy sources to draft a reminder with three targets and citations; do not send'],['依据天文资料做一份足够精彩的活动方案','Make an exciting event plan using astronomy sources'],['收集本月天文信息，挑出最有价值的内容','Collect this month’s astronomy information and choose the most valuable items']],['成果、数量、资料范围与停止点明确，才有共同的检查依据。','A deliverable, count, source scope, and stopping point provide shared checks.']),
  5:q(['任务是比较三家配件价格，没有购买授权。哪种下一步合适？','The task is to compare accessories at three stores, with no purchase authorization. What fits?'],[['比较价格、规格与退换条件，交付推荐供人决定','Compare prices, specifications, and returns and hand over recommendations'],['低于预算就下单，之后展示订单','Order below budget and show the receipt afterward'],['先付可退款订金，再请负责人确认','Pay a refundable deposit before asking for confirmation']],['预算和可退款不等于购买授权；付款前要取得相应确认。','A budget or refund option is not purchase authorization; confirmation must precede payment.']),
  6:q(['两份资料的流星雨峰值日期冲突，先怎样处理？','Two sources disagree on a meteor shower’s peak date. What first?'],[['核对年份、时区和适用地区，无法解决时标出冲突并报告','Check year, time zone, and region; report unresolved disagreement'],['取两个日期的中间一天作为折中','Choose the midpoint between the dates'],['只保留更新的一页，不核对它描述的地区','Keep only the newer page without checking its region']],['表面日期差异可能来自范围不同，发布时间也不是准确性的充分证据。','Scope may explain date differences, and recency alone does not establish accuracy.']),
  7:f(['检查结果未满足目标时，应在许可范围内修改，或者___。','If a result fails the goal, revise within permission or ___.'],[['停止并报告','stop and report'],['自动扩大权限','automatically expand permissions'],['省略完成条件','omit completion checks']],['执行失败不产生新的授权，也不能通过降低标准假装完成。','Failure does not grant new permissions or justify pretending completion.']),
  8:f(['任务只允许写通知，尚未批准发送，此时交付___。','With drafting allowed but sending not approved, deliver a ___.'],[['可审阅的草稿','reviewable draft'],['已发送的通知','sent notice'],['公开的通知链接','public notice link']],['交付草稿满足当前范围；发送和公开是额外动作。','A draft satisfies current scope; sending and publishing are additional actions.']),
  9:f(['事先列出能访问的网站、文件和功能，是设置工具___。','Listing permitted websites, files, and functions defines a tool ___.'],[['白名单','allowlist'],['执行日志','execution log'],['结果缓存','result cache']],['白名单限制可用范围；日志记录已发生的事，缓存复用已得到的结果。','An allowlist limits access; logs record events and caches reuse results.']),
  10:q(['活动提醒确实需要城市以查天气，不需要街道地址。怎样收集信息？','A reminder needs the city for weather, not a street address. How should data be collected?'],[['说明用途，只询问城市，按约定保存','Explain the purpose, ask only for the city, and retain it as agreed'],['同时询问街道地址，以备以后使用','Ask for the street address too for possible future use'],['从照片猜精确定位，以免打扰用户','Infer exact location from photos to avoid asking']],['只收集实际必要且获准的信息；方便以后使用不是扩展收集的理由。','Collect only necessary, authorized information; possible future convenience is not sufficient.']),
 12:m(['按本题指定的任务条件，配对合适的处理方式。','Match each specified task to a suitable approach.'],[
   [['只把一句通知改得礼貌一些','Polish one sentence for politeness'],['Chat：直接讨论与改写','Chat: discuss and rewrite']],
   [['每日定时按固定步骤汇总三家价格','Summarize three stores daily with fixed steps'],['Workflow：运行预设流程','Workflow: run a predefined process']],
   [['资料失效后需在获准来源内自主规划补查','Replan research among approved sources after a source fails'],['Agent：依据结果选择后续行动','Agent: select later actions from results']],
   [['决定是否付款购买','Decide whether to pay for a purchase'],['本课由负责人确认','Owner confirmation in this course']]]),
 13:m(['把概念误解与对应说明配对。','Match misconceptions to their corrections.'],[
   [['接了搜索就一定是 Agent','Search access alone makes an agent'],['还要看谁决定下一步以及如何检查','Also inspect how next actions are selected and checked']],
   [['Workflow 不能包含任何条件判断','Workflows cannot have conditions'],['可以包含预先设计的分支和循环','They can contain predefined branches and loops']],
   [['Agent 的定义就是不能发送','An agent is defined by inability to send'],['发送能力与权限策略不同，本课要求先确认','Capability differs from permission; this course requires confirmation']],
   [['Chat 只能一问一答','Chat allows only one turn'],['聊天可以多轮，轮数不决定是否自主行动','Chat can span turns; turn count does not establish agentic action']]]),
 14:m(['根据场景中明确给出的限制配对。','Match each scenario to its stated constraint.'],[
   [['比较价格，但没有付款授权','Compare prices with no payment permission'],['停在推荐清单，不下单','Stop at recommendations; do not order']],
   [['海报含同学照片，尚未取得使用许可','Poster uses a classmate’s photo without permission'],['先解决肖像使用与隐私问题','Resolve image permission and privacy first']],
   [['一次性文字润色，不需要外部工具','One-off text polish with no tools needed'],['直接聊天即可，不必搭建行动循环','Chat is enough; no action loop needed']],
   [['每天按相同公式汇总固定表格','Daily totals using the same formula and table'],['使用预设流程即可，不必自主改计划','A predefined process suffices; no adaptive planning needed']]]),
 15:m(['把执行现象与针对性的下一步配对。','Match execution evidence to a targeted next step.'],[
   [['建议缺少任务要求的来源','Recommendations lack required sources'],['补齐并核对证据后再交付','Add and verify evidence before delivery']],
   [['已达到约定的尝试次数上限','The agreed attempt limit has been reached'],['停止该尝试并报告失败记录','Stop attempts and report the failure record']],
   [['下一步要发送，尚无批准','Sending is next, but approval is absent'],['暂停在发送前请求对应确认','Pause before sending for applicable approval']],
   [['持续运行后发现全部动作都是固定规则','All recurring actions follow fixed rules'],['考虑用工作流简化维护','Consider a workflow to simplify maintenance']]]),
 },
 '4-2':{
  1:q(['要为七年级书社拟五本科幻书单，哪条 Goal 最可检查？','Which Goal is most checkable for a grade-seven science-fiction book list?'],[['五本书，每本附允许目录中的来源与适龄依据，只输出草稿','Five books, each with an approved-catalog source and age-suitability evidence; draft only'],['五本最值得看的书，来源可以稍后补','Five must-read books; add sources later'],['让书社喜欢这份书单，数量由助手判断','Make a list the club likes; let the assistant decide the count']],['数量、证据和交付边界要同时清楚，不能只看书单长度。','Count, evidence, and delivery scope must all be clear; length alone is insufficient.']),
  2:q(['“确认主题→查目录→核对适龄依据→起草”属于哪个字段？','Which field contains “confirm topic → inspect catalog → check age evidence → draft”?'],[['Plan：准备执行的步骤','Plan: intended steps'],['State：当前已知结果','State: current known results'],['Done：结束所需条件','Done: completion criteria']],['Plan 说明准备怎么做；State 是现状，Done 用于判定是否完成。','Plan describes intended work; State records the present and Done defines completion.']),
  3:q(['State 记录“草稿 v2 已批准”，随后修改了时间并生成 v3。新状态应该怎样写？','State says draft v2 is approved. The time changes in v3. What should the new state say?'],[['currentVersion=v3，approval=pending，等待重新核对','currentVersion=v3, approval=pending; await renewed review'],['currentVersion=v3，approval=approved，沿用 v2','currentVersion=v3, approval=approved; reuse v2 approval'],['只保留 approval=approved，删掉版本号','Keep approval=approved and omit the version']],['批准对应具体版本；内容变化后不能把旧批准套到新稿。','Approval applies to a specific version; changed content cannot inherit it automatically.']),
  4:q(['已核对两本书，第三本缺出版社记录。哪个 State 最有助于接着做？','Two books are verified; the third lacks a publisher record. Which State best supports resuming?'],[['已核对书1/2及来源；书3证据缺失；下一步查获准备用目录','Books 1/2 and sources verified; book 3 evidence missing; next check approved backup catalog'],['处理得不错，继续即可','Progress is good; continue'],['把整个聊天复制进去，不标当前步骤','Copy the entire chat without identifying the current step']],['状态需要保留结果、证据、卡点与下一步，便于恢复而不重复做。','A useful state records results, evidence, blockers, and next action for reliable resumption.']),
  5:q(['规则是“初次查找加一次重试，仍无证据就报告”。两次查找均失败，现在怎么办？','The rule allows an initial lookup and one retry, then requires a report if evidence is absent. Both failed. What now?'],[['记录两次尝试和缺失证据，停止尝试并请求帮助','Record two attempts and missing evidence; stop and request help'],['再查两次，因为“两次”指失败后的重试','Try twice more because two means retries after failure'],['用相似书目资料补齐，让 Done 通过','Use a similar book’s data to satisfy Done']],['一次初试加一次重试合计两次；失败不能用别的书的数据伪装成功。','One initial attempt plus one retry is two total; unrelated data cannot turn failure into success.']),
  6:q(['书单任务只需年级、主题与公开目录，哪项应从输入中移除？','The list needs grade, topic, and public catalogs only. Which input should be removed?'],[['报名同学的住址和电话号码','Participants’ home addresses and phone numbers'],['允许访问的目录地址','Approved catalog addresses'],['书单数量与草稿格式','Book count and draft format']],['住址与电话和本任务无关，属于不必要的个人信息。','Addresses and phone numbers are unnecessary personal data for this task.']),
  7:f(['五格任务单中，“最后要交什么”由___描述。','In the five-field task card, the final deliverable is described by ___.'],[['Goal','Goal'],['State','State'],['Task','Task']],['Goal 定义成果；Task 是当前动作，State 记录实际进展。','Goal defines the result; Task is the current action and State records actual progress.']),
  8:f(['“已核对两项，第三项缺来源，下一步补查”应写入___。','“Two verified, the third lacks a source, next inspect backup” belongs in ___.'],[['State','State'],['Goal','Goal'],['Done','Done']],['这是一张进展快照，不是目标本身或完成标准。','This is a progress snapshot, not the goal or completion criteria.']),
  9:f(['用“数量齐全、来源已核对、草稿已保存”判断能否结束，对应___。','Checking count, verified sources, and a saved draft corresponds to ___.'],[['Done','Done'],['Plan','Plan'],['Task','Task']],['Done 检查可观察的结果，而不是只接受“我完成了”的声明。','Done checks observable results rather than accepting a declaration of completion.']),
 10:q(['Done 要求五本书都有来源，目前五本齐全但一本缺来源。应判定为什么？','Done requires sources for all five books. Five titles exist, but one lacks a source. What is the status?'],[['尚未完成，补证据或报告阻塞','Incomplete; obtain evidence or report a blocker'],['已完成，因为数量满足','Complete because the count is met'],['已完成，只要文字读起来流畅','Complete if the prose reads smoothly']],['完成条件必须一起满足；数量或文笔不能代替证据。','All required conditions must hold; count or fluent prose cannot substitute for evidence.']),
 12:m(['把任务字段与具体内容配对。','Match task fields to concrete entries.'],[
   [['Goal','Goal'],['输出五本适龄科幻书的来源清楚的草稿','Deliver a sourced draft of five age-suitable science-fiction books']],
   [['Plan','Plan'],['确认主题→查目录→核对→起草','Confirm topic → inspect catalogs → verify → draft']],
   [['Task','Task'],['现在核对第三本书的出版信息','Currently verify publication information for book three']],
   [['State','State'],['前两本已核对，第三本缺证据，尝试次数为1','First two verified; third lacks evidence; attempts=1']],
   [['Done','Done'],['五本均有核实来源，草稿已保存，未发送','Five verified sources; draft saved; not sent']]]),
 13:m(['把发生的事件与对应 State 更新配对。','Match events to corresponding State updates.'],[
   [['草稿 v2 经负责人明确批准','Owner explicitly approves draft v2'],['approval=approved，approvedVersion=v2','approval=approved, approvedVersion=v2']],
   [['批准后又改成草稿 v3','Approved draft is edited into v3'],['currentVersion=v3，approval=pending','currentVersion=v3, approval=pending']],
   [['本次来源查询失败','This source lookup fails'],['增加 attempts 并记录错误与缺失项','Increment attempts; record error and missing evidence']],
   [['达到上限仍无来源','Attempt limit reached without evidence'],['status=blocked，等待新资料或决定','status=blocked; await evidence or a decision']]]),
 14:m(['把未满足的依赖与直接后果配对。','Match unmet dependencies to their direct consequence.'],[
   [['当前版本尚未批准','Current version is not approved'],['不得进入发送动作','Do not enter the sending action']],
   [['书目来源尚未核实','Book sources are not verified'],['不得标记“来源检查通过”','Do not mark source verification passed']],
   [['草稿文件未成功保存','Draft file has not been saved successfully'],['不得把“草稿已保存”记为真','Do not mark the saved-draft condition true']],
   [['查找已用完允许次数','Allowed lookup attempts are exhausted'],['不得继续同一重试循环','Do not continue that retry loop']]]),
 15:m(['把常见误解与对应修正配对。','Match common misconceptions to corrections.'],[
   [['State 只是完整聊天备份','State is simply a full chat backup'],['应提炼当前版本、证据、状态和卡点','Capture current version, evidence, status, and blockers']],
   [['模型说完成就等于 Done','The model saying done establishes Done'],['逐项核对事先定义的完成条件','Check each predefined completion condition']],
   [['审批后任何改稿都沿用批准','All later edits inherit approval'],['批准应绑定被核对的版本','Bind approval to the reviewed version']],
   [['计划一旦写下就不能改','A plan can never change'],['根据新证据在原授权内更新计划与状态','Update plan and state from evidence within existing permission']]]),
 },
};

export const FOUNDATION_PRACTICES:Record<string,Both>={
 '4-1':p(['为三项任务选择 Chat、Workflow 或 Agent，并各写一句理由：润色一句通知；每天按固定规则汇总值日表；获准使用的来源失效后，需要自主选择备用调查步骤。最后写出一个本课需要负责人确认的外部动作。','Choose Chat, Workflow, or Agent for polishing one sentence, summarizing a duty roster daily with fixed rules, and adaptively choosing research steps when an approved source fails. Explain each and name one external action requiring owner confirmation in this course.'],['三项任务各有选择与理由；自适应调查不超出许可；列出需确认的动作。','Explain each choice, keep adaptive research within permission, and name an action requiring confirmation.'],['Chat 适合直接改写一句话；Workflow 适合每日重复的固定规则；Agent 可在允许的来源中依据失败结果选择下一步。向班群发送通知需负责人核对内容与受众后确认。','Chat suits a direct sentence rewrite. A workflow suits repeated fixed rules. An agent can select the next step among approved sources based on failures. Sending to the class group requires owner review of content and audience.']),
 '4-2':p(['用 Goal、Plan、Task、State、Done 五格描述“准备周末观影通知，只出草稿”。已知：周六15:00、学校报告厅、面向电影社；初稿 v1 已写好，但负责人尚未核对时间。写当前快照，再写负责人要求改到16:00后应怎样更新。','Use Goal, Plan, Task, State, and Done for preparing a weekend film notice, draft only. Facts: Saturday 15:00, school hall, film club. Draft v1 exists; the owner has not verified the time. Write the current snapshot and update it after the owner requests 16:00.'],['五格都有具体内容；State 记录版本与未核对项；改稿后保持待核对，Done 不提前成立；不发送。','Fill all five fields. Track version and unverified facts. After edits, keep review pending and Done false; do not send.'],['Goal：观影通知草稿，列时间地点受众，不发送。Plan：核对资料→起草→负责人核对→保存确认稿。Task：等待时间核对。State：currentVersion=v1，approval=pending，未核对时间。Done：时间地点已确认、当前草稿已核对并保存、未发送。收到16:00修改意见后：把时间改为16:00，版本更新v2，approval=pending，请负责人核对v2；此时 Done=false。','Goal: draft a film notice with time, place, and audience; no sending. Plan: verify facts → draft → owner review → save reviewed version. Task: await time verification. State: currentVersion=v1, approval=pending, time unverified. Done: time/place confirmed, current draft reviewed and saved, not sent. After the 16:00 request: update time and version to v2, keep approval=pending, and request review of v2. Done is still false.']),
};

export const FOUNDATION_THEORY:Record<string,Bilingual[]>={
 '4-1':[
  ['**三种方式，没有高低排名**\nChat 可以多轮讨论；Workflow 按预设步骤、分支或循环执行；Agent 能依据结果围绕目标选择后续行动。产品常把它们组合起来。接入搜索或记住对话，并不能单独证明它是 Agent。','**Three approaches, not a ranking**\nChat supports multi-turn discussion. Workflows execute predefined steps, branches, or loops. Agents select later actions toward a goal using results. Products often combine them; search access or conversation memory alone does not establish agentic behavior.'],
  ['**根据任务选方式**\n一句话润色用聊天即可；每日固定来源的汇总适合工作流；需要依据新情况规划补查时，可以使用受控 Agent。多步任务也可以是工作流，不必为了步骤多就上 Agent。','**Choose for the task**\nChat can polish a sentence; a workflow can summarize fixed sources daily. Adaptive research may suit a controlled agent. Multiple steps alone do not require an agent.'],
  ['**目标与许可分别写清**\n例如：用两份指定公开资料写观星活动草稿，列三个观察对象及来源，不发送。白名单列出允许的网站、文件和功能；允许查资料不等于允许联系他人。','**Specify the goal and permissions**\nExample: use two named public sources to draft a stargazing notice with three targets and citations; do not send. An allowlist names permitted sites, files, and functions. Research permission does not imply permission to contact others.'],
  ['**本课的行动边界**\n练习只用必要且获准的资料，不填写密码、证件号或无关个人信息。付款、发送、删除和公开前由负责人确认。实际产品可能有不同授权方式；这是本课采用的安全规则，不是 Agent 的定义。','**Action boundaries in this course**\nUse only necessary, authorized information; omit passwords, identity numbers, and unrelated personal data. Require owner confirmation before payment, sending, deletion, or publishing. Products can use different authorization designs; this is the course policy, not the definition of an agent.'],
  ['**检查后修改或停止**\n日期冲突时核对年份、时区与地区；缺证据时不编造。改计划仍受原来的许可与尝试次数限制。完成条件满足，或无法继续时，都应停止并交代结果。','**Check, revise, or stop**\nResolve date conflicts by checking year, time zone, and region. Do not invent missing evidence. Revised plans still obey permission and attempt limits. Stop with a clear result when complete or unable to proceed.'],
  ['**把合适的工作交给合适的方式**\n保存你的三项选型与理由，记住：能力、任务需求与授权范围要分别判断。','**Match the approach to the work**\nKeep your three selections and reasons. Judge capability, task needs, and permission separately.'],
 ],
 '4-2':[
  ['**五格任务单**\nGoal：最后交什么；Plan：准备怎么做；Task：当前这一步；State：已知结果、证据与卡点；Done：能否结束的可检查条件。例如“草稿v1已写好、时间未核对、等待确认”是 State，不代表 Done。','**Five-field task card**\nGoal: final result. Plan: intended steps. Task: current action. State: known results, evidence, and blockers. Done: observable completion conditions. “Draft v1 exists, time unverified, awaiting review” is a State, not proof of Done.'],
  ['**把 Goal 展开写清**\n成果、受众、范围格式、允许资料、禁止动作、停止条件，是给五格补充细节，不是另一套替代框架。例如：面向电影社的周末通知草稿；用已确认的时间地点；不发送；缺信息就报告。','**Add detail to Goal**\nDeliverable, audience, scope/format, allowed sources, forbidden actions, and stopping rules add detail to the five fields; they do not replace them. Example: a weekend film-club notice draft using confirmed time/place; no sending; report missing facts.'],
  ['**一张已填的任务单**\nGoal：通知草稿。Plan：核对→起草→复核→保存。Task：核对时间。State：v1已写好，时间待确认，approval=pending。Done：时间地点已确认、当前稿已复核并保存、未发送。pending 表示等待；approved 表示这一版已批准；blocked 表示缺少必要条件而暂停。','**A filled-in card**\nGoal: notice draft. Plan: verify → draft → review → save. Task: verify time. State: v1 exists, time unconfirmed, approval=pending. Done: time/place confirmed, current draft reviewed and saved, not sent. Pending means awaiting a decision; approved applies to a reviewed version; blocked means a necessary condition is missing.'],
  ['**状态随结果更新**\n每步后记录当前版本、证据、错误和尝试次数。初次查找加一次重试就是两次尝试。失败达到上限就进入 blocked 并报告；不是重新把计数归零。审批绑定版本，改稿后重新等待核对。','**Update state from results**\nRecord current version, evidence, errors, and attempt count after each action. One initial lookup plus one retry is two attempts. At the failure limit, mark blocked and report; do not reset the count. Approval is version-bound; edits require renewed review.'],
  ['**完成要看实际条件**\n五本书齐了，但一本没有来源，仍不满足“每本有核实来源”。同样，旧版本批准不等于新版本批准。只收集本任务需要且获准的信息；本课外部发送前仍需负责人确认。','**Check actual completion conditions**\nFive titles with one missing source do not satisfy “verified source for every book.” Approval of an old version does not approve a new one. Collect only needed, authorized data; external sending in this course still requires owner confirmation.'],
  ['**留下可继续的快照**\n保存五格任务单和更新后的版本、状态，让下一次打开时能知道做到哪、缺什么、下一步做什么。','**Leave a resumable snapshot**\nKeep the five-field card and updated version/state so the next session knows what is done, what is missing, and what comes next.'],
 ],
};

export const FOUNDATION_LABS:Record<string,Both>={
 '4-2':[0,1].map(lang=>({type:'interactive',interactiveKind:'sequence',interactiveTitle:lang?'Update a task from evidence':'根据结果更新任务',interactiveInstruction:lang?'Draft only. The time is confirmed. Arrange this successful path from defining the deliverable to checking completion. State will be updated after every action; one update is shown here.':'任务只出草稿，时间已确认。按依赖排出从定义成果到检查完成的成功路径。状态每步都会更新，这里展示起草后的一次更新。',interactiveSequence:lang?['Define Goal and completion conditions','Plan: draft, review, then save','Execute Task: write draft v1','Update State: v1 ready, review pending','Obtain review of v1 and save it','Check Done against the saved, reviewed version']:['定义 Goal 与完成条件','制定 Plan：起草、复核、保存','执行 Task：写出草稿 v1','更新 State：v1就绪，复核待完成','取得 v1 的复核结果并保存','按已复核的保存稿检查 Done']})) as Both,
};
