import {q,f,m,p,type Both,type Bilingual} from './course-fix-builders';
import {MEDIA_COMPLETIONS} from './course-fixes-media-completion';
export const MEDIA_QUESTIONS:Record<string,Record<number,Both>>={
 '3-1':{
  1:q(['教学模型把 224×224 图片切成不重叠方块，不加其他 Token。比较 Patch 边长16和14，块数分别是多少？','A toy model splits a 224×224 image into non-overlapping squares with no additional tokens. How many patches for side lengths16 and14?'],[['196 与 256，后者块数更多','196 and 256; the latter has more patches'],['14 与16，直接把每边块数当总数','14 and16, treating patches per side as the total'],['256 与196，块越小数量越少','256 and196; smaller patches mean fewer patches']],['每边分别14或16块，总数要平方。此题比较架构设定，不代表普通用户能修改成品模型的 Patch。','There are14 or16 patches per side; square them for totals. This compares architecture settings, not a user-adjustable patch option in every product.']),
  3:q(['模型把停车标志描述成披萨，仅凭这个结果能确定唯一故障环节吗？','A model describes a stop sign as pizza. Can this alone identify a unique failing component?'],[['不能，先检查输入、可见细节和重复测试，再定位视觉表示或图文对应等可能问题','No; inspect input, visible details, and repeated tests before isolating possible representation or alignment issues'],['能，一定是图文对齐训练失败','Yes; alignment training must have failed'],['能，一定是图片分辨率过低','Yes; the image resolution must be too low']],['错误描述是现象，唯一根因需要更多证据。','An incorrect description is a symptom; a unique root cause needs more evidence.']),
  4:q(['固定图像尺寸，在这个简化切块模型中减小 Patch，哪条说法更准确？','At fixed image dimensions in this toy patch model, what does a smaller patch imply?'],[['块数增加、计算需求可能增加，但准确率仍需测试','More patches and potentially more computation; accuracy still needs testing'],['块数增加，所以任何任务准确率必然提高','More patches guarantee greater accuracy on every task'],['块数变少，所以成本必然下降','Fewer patches guarantee lower cost']],['更多细粒度表示不等于必然更准确，噪声与模型能力也有影响。','Finer representation does not guarantee accuracy; noise and model capability matter.']),
  5:q(['现成图文工具提供“低/高细节”但没有 Patch 开关。只需粗看整图，怎样起步？','An image tool offers low/high detail but no patch control. For a rough overview, how should you start?'],[['先用低细节检查，信息不足再提高细节或裁切','Start with low detail; increase it or crop if evidence is insufficient'],['在提示词里要求 Patch=32，假定架构已经改变','Write Patch=32 in the prompt and assume the architecture changed'],['直接认定最高细节对所有任务成本更低','Assume the highest detail costs less for every task']],['使用工具实际支持的选项，不把架构参数当成通用按钮。','Use controls the tool actually supports; architecture parameters are not universal controls.']),
  7:q(['同一个模型的 Patch 由架构固定，小字看不清时用户通常能控制什么？','If a model’s patch size is fixed by its architecture, what can a user usually adjust for unreadable small text?'],[['提供清晰裁图，或使用工具支持的细节档位','Provide a clear crop or use supported detail settings'],['直接替换模型内部 Patch 权重','Directly replace internal patch weights'],['只修改答案语言就增加原图细节','Change response language to add detail to the source image']],['更清楚的输入提供可见证据；文字提示不能创造原图没有的细节。','Clear input supplies visual evidence; instructions cannot create missing source detail.']),
  9:q(['图文相似度很高意味着什么？','What does a high image-text similarity score imply?'],[['模型认为对应关系较强，但具体事实仍需对照图片','The model finds a strong correspondence; facts still need image checks'],['图中每一个数字已经核实','Every number in the image is verified'],['图片已获得公开使用许可','Publication permission has been established']],['相似性、事实与授权是不同问题。','Similarity, factual accuracy, and permission are distinct.']),
  10:q(['同图有时读出1,000m、有时100m。要单独检查输入分辨率的影响，怎样做？','The same image yields1,000m or100m. How can you isolate the effect of resolution?'],[['固定模型、问题和裁切范围，只改变分辨率，重复读取并对照原图','Fix model, question, and crop; vary only resolution, repeat, and compare with the source'],['同时换模型、裁图和提示，再归因给分辨率','Change model, crop, and prompt and attribute the result to resolution'],['取平均550m作为稳定答案','Average to550m as a stable answer']],['对照实验只能支持被控制的变量；正确读数还要看原图证据。','A controlled comparison supports the varied factor; the correct reading still needs source evidence.']),
  14:m(['把用户能做的操作与明确目的配对。','Match user-accessible actions to their specific purpose.'],[
   [['裁出原图中的小字区域','Crop the small-text area from the original'],['减少无关画面，集中核对文字','Reduce irrelevant content and focus text verification']],
   [['在工具提供时先用低细节模式','Use low detail first when offered'],['低成本完成初步整图概览','Obtain an initial overview at lower cost']],
   [['固定其他条件，只改一个输入设置','Fix other conditions and vary one input setting'],['检查该设置的影响','Test the effect of that setting']],
   [['保留多次输出并与原图对照','Retain repeated outputs and compare with the original'],['检查稳定性，避免只挑一次命中','Check stability instead of selecting one lucky result']]]),
  15:m(['把常见误解与准确说明配对。','Match misconceptions to accurate qualifications.'],[
   [['小 Patch 必定更准确','Smaller patches guarantee accuracy'],['块数与成本变化不能替代准确性测试','Patch count and cost changes do not replace accuracy testing']],
   [['所有图文模型都使用同一编码器结构','Every vision-language model uses the same encoder'],['架构存在差异，本课链路是简化示意','Architectures differ; this lesson is a simplified illustration']],
   [['图文对齐分数高就不用查图','High alignment score removes the need to inspect the image'],['相似不代表每个细节属实','Similarity does not establish every detail']],
   [['一次正确就说明始终稳定','One correct answer proves stability'],['应复测并保留失败样本','Repeat tests and retain failures']]]),
 },
 '3-2':{
  1:q(['图片中的“2026”读成“2028”，先检查哪组输入条件？','An image’s “2026” is read as “2028.” Which input conditions should you check first?'],[['文字清晰度、遮挡、倾斜与对比度','Text clarity, occlusion, tilt, and contrast'],['回答的语气、段落数与称呼','Response tone, paragraph count, and form of address'],['图表的统计口径与样本范围','Chart aggregation method and sample scope']],['本题直接观察到字符误读，先检查字符的可见证据；还不能确定唯一根因。','The observed failure is a character misread. Inspect visible text evidence first; a unique cause is not yet established.']),
  2:q(['图中确实是路灯，回答把它说成人。这首先属于哪类可观察的错误？','The object is a street lamp, but the answer calls it a person. What observed error is this?'],[['对象类别识别错误','Object-category recognition error'],['图中文字识别错误','Text-recognition error'],['两个物体的左右关系反转','Reversed left-right relationship between two objects']],['这是物体认错的现象，不足以断言模型内部哪一层出了问题。','This identifies an object misclassification, not a specific faulty internal layer.']),
  3:q(['按观察者视角，杯子在书前，回答却说书在杯前。错误在哪里？','From the viewer’s perspective, a cup is in front of a book, but the answer reverses this. What is wrong?'],[['空间关系反转','Spatial relationship is reversed'],['杯子文字转写有误','Text on the cup is mistranscribed'],['物体数量计算有误','Object count is incorrect']],['主体都认出了，但前后关系不符合给定视角。','The objects were identified, but their relative position contradicts the specified viewpoint.']),
  4:q(['纵轴单位为“千人”，柱值为3，回答写“3人”。哪个环节读错？','A chart uses thousands of people; a bar reads 3, but the answer says 3 people. What was missed?'],[['没有把图表单位用于解释数值','The chart unit was not applied to the value'],['把柱子的颜色当成类别','The bar color was treated as a category'],['把横轴顺序当成时间趋势','Category order was treated as a time trend']],['3千人是3000人。读到数字还要结合单位与刻度。','Three thousand is 3,000 people. Values must be interpreted with units and scale.']),
  5:q(['想检验“裁图删掉周围信息影响了回答”，哪个比较最合适？','How should you test whether removing surrounding context by cropping affects an answer?'],[['固定模型与问题，比较原图和裁图，记录每次结果','Fix model and question; compare original and crop and record all results'],['原图用模型A，裁图用模型B，再比较','Use model A for the original and B for the crop'],['裁图同时提高清晰度并换问题，再归因给上下文','Sharpen the crop and change the question, then attribute differences to context']],['只改裁切范围才能更好地隔离影响；还应留意工具是否自动缩放输入。','Varying only the crop better isolates its effect; also note automatic tool resizing.']),
  6:q(['模糊图的读数多次变化，怎样检查清晰度的影响？','Readings of a blurry image vary across runs. How can you test clarity’s effect?'],[['同图清晰版与模糊版、同模型同问题，各重复读取并与原图核对','Use clear and blurred versions, the same model/question, repeat both, and check against the original'],['清晰版只试一次，模糊版一直试到答对','Try the clear version once and the blurry one until correct'],['两组都只保留最接近预期的答案','Keep only the closest-to-expected answer from each group']],['保留全部结果才能比较稳定性，不能只挑成功样本。','Retaining all results supports a stability comparison; selecting successes does not.']),
  7:f(['把图片中的字符读成文字，通常叫___。','Reading characters in an image into text is called ___.'],[['OCR','OCR'],['对象识别','object recognition'],['空间关系判断','spatial reasoning']],['OCR 关注字符；对象识别和空间判断关注物体类别与位置关系。','OCR focuses on characters; object recognition and spatial reasoning concern categories and relative positions.']),
  8:f(['按明确视角判断谁在谁前后左右，是___理解。','Reasoning about front, back, left, and right from a stated viewpoint is ___ understanding.'],[['空间关系','spatial-relation'],['文字转写','text-transcription'],['数量统计','object-count']],['视角和参照物要清楚，左右不能脱离参照来判断。','A viewpoint and reference object are necessary for meaningful left-right judgments.']),
  9:f(['图表中“3”代表3人还是3000人，需要结合坐标轴的___。','Whether a chart’s 3 means 3 or 3,000 people depends on the axis ___.'],[['单位','unit'],['颜色','color'],['位置','position']],['“千人”与“人”相差千倍；读数应同时报告单位。','Thousands of people differs from people by a factor of 1,000; report the unit with the value.']),
 10:q(['原图可核对为3.5，同模型同问题读模糊版得到8.5。怎样记录最准确？','The original verifies 3.5; the same model/question reads a blurred version as 8.5. What should the record say?'],[['这次模糊版读错，保留两图与结果；复测后再判断稳定性','This blurred reading was wrong; keep both images/results and repeat before judging stability'],['已证明该模型所有小数都读不对','The model cannot read any decimals'],['平均为6.0，可作为纠正后的事实','Their average, 6.0, is the corrected fact']],['一次受控比较给出本次差异，不能推到全部场景；平均错误读数也不会产生图中事实。','One comparison establishes this difference, not a universal failure; averaging misreads does not recover source facts.']),
 11:p(['选一张自己可使用、没有个人信息且文字清楚的图片，制作一张模糊副本。用同一图文工具和同一问题分别读取，每版至少试两次。记录原图可核对的文字、各次答案和差异；即使没有读错也照实记录。','Choose a clear text image you may use, with no personal data, and make a blurred copy. Use the same vision tool and question for both, at least twice each. Record verified source text, every answer, and differences; report unchanged results honestly too.'],['清晰版与模糊版来自同图；固定模型和问题；各两次结果；对照原图解释观察及局限。','Use the same source, model, and question; record two runs per version; explain observations and limits against the original.'],['记录格式：来源及可用依据；原文；固定工具/问题；清晰版两次；模糊版两次；观察与下一步。示例：原文12km；清晰版12km/12km，模糊版72km/12km；本次模糊条件下结果不稳定，可能与字符边缘丢失有关，需要更多样本验证。请填写自己实际得到的结果。','Record: source and permission; verified text; fixed tool/question; two clear runs; two blurry runs; observation and next step. Example: source 12km; clear 12km/12km; blurry 72km/12km. This blurry condition was unstable, possibly due to lost character edges; more samples are needed. Fill in your actual results.']),
 12:m(['把观察到的错误与类别配对。','Match observed errors to their category.'],[
   [['把B2读成82','Reads B2 as 82'],['字符识别错误','Character-recognition error']],
   [['把椅子认成书包','Calls a chair a backpack'],['对象类别错误','Object-category error']],
   [['杯子在瓶左，却说在瓶右','Cup is left of bottle, answer says right'],['空间关系错误','Spatial-relation error']],
   [['图示比例为20%，回答称20人','Chart shows 20%, answer says 20 people'],['图表量纲错误','Chart-unit error']]]),
 13:m(['把对照设计与直接能检查的内容配对。','Match comparison designs to what they directly test.'],[
   [['只改变裁切范围','Vary only crop boundaries'],['被移除的周边信息是否影响回答','Whether removed context affects the answer']],
   [['只增加同图的模糊程度','Vary only blur on the same image'],['清晰度变化是否影响读取','Whether clarity affects reading']],
   [['相同设置下重复读取','Repeat readings at the same settings'],['输出在这些设置下是否稳定','Whether output is stable at those settings']],
   [['同时换模型、提示和图片','Change model, prompt, and image together'],['无法单独归因给其中一个改动','Cannot isolate attribution to one change']]]),
 14:m(['每项已给出待核查的具体线索，选择对应动作。','Match each specific diagnostic clue to an action.'],[
   [['要读的文字在原图只占很小区域','Target text occupies a tiny part of the original'],['提供清晰原图的文字裁图再核对','Provide a clear original-text crop and recheck']],
   [['“左边”未说明相对哪个物体','“Left” has no reference object'],['指定参照物与观察视角','Specify reference object and viewpoint']],
   [['图表答案比标注单位少了千倍','Answer omits the chart’s thousand multiplier'],['核对单位并重新换算','Check the unit and convert again']],
   [['照片物体被遮挡，看不出类别','Occlusion prevents identifying the object'],['报告不可判断，索取更完整视图','State uncertainty and request a fuller view']]]),
 15:m(['把推断与它缺少的限定配对。','Match claims to missing qualifications.'],[
   [['裁图更聚焦就一定更准','A tighter crop is always more accurate'],['裁切也可能丢失必要上下文','Cropping may remove necessary context']],
   [['放大模糊图即可恢复原文字','Enlarging blur restores the original text'],['插值不能保证恢复丢失的字符细节','Interpolation does not guarantee recovery of missing character detail']],
   [['回答很肯定就说明看清了','A confident answer proves clear perception'],['语言自信不能代替原图证据','Verbal confidence does not replace source evidence']],
   [['一次识别正确就说明一直稳定','One correct reading proves stability'],['需多次测试并保留失败记录','Repeat tests and retain failures']]]),
 },
 '3-3':{
  4:q(['固定提示、模型和尺寸，只改变 Seed。合理预期是什么？','With prompt, model, and dimensions fixed, what can changing only Seed do?'],[['改变随机起点，构图、身份与细节都可能变化','Change the random starting point; composition, identity, and details may all change'],['只改小细节，构图与人物身份必然保持','Change only minor details while preserving composition and identity'],['只改变文件编号，画面完全不变','Change only the file ID, leaving the image unchanged']],['相同提示仍提供主题约束，但新 Seed 不保证原构图或身份。','The prompt still constrains the topic, but a new seed does not preserve composition or identity by guarantee.']),
  5:q(['图片偏离主题，而工具没有 CFG 控件。怎样先排查？','An image misses the topic, and the tool has no CFG control. What should you inspect first?'],[['检查主体、动作与关系是否明确，再只改一处提示复测','Check whether subject, action, and relationships are explicit; change one prompt element and retest'],['在任何工具里输入 CFG=8 就能启用','Typing CFG=8 enables it in every tool'],['只增加去噪步数就能保证不偏题','More denoising steps guarantee prompt adherence']],['参数因模型和产品而异，使用实际可用的控制。','Parameters vary by model and product; use available controls.']),
  9:q(['要尽量复现一次生成，除了 Seed 还应记录什么？','Besides Seed, what should you record for reproducibility?'],[['模型及版本、提示、尺寸、采样设置和可用环境信息','Model/version, prompt, dimensions, sampling settings, and available environment information'],['只记录图片名称即可','Only the image filename'],['只记录最终画面中的主色','Only the dominant output color']],['同 Seed 不同模型或设置可能完全不同，部分服务即使参数相同仍不能保证逐像素复现。','The same seed with different models/settings can differ greatly; some services cannot guarantee pixel-exact reproduction even with matching settings.']),
  13:m(['下面是已经观察到的线索，选择对应的排查动作，不把症状直接等同根因。','Match observed evidence to a diagnostic action, not a claimed unique cause.'],[
   [['提示没说明要画哪个主体','Prompt does not identify the intended subject'],['补明确主体，其余条件固定复测','Specify the subject and retest with other conditions fixed']],
   [['想检查 Steps 对边缘细节的影响','Want to test Steps against edge detail'],['固定其他设置，比较不同步数的边缘与耗时','Fix other settings; compare edge quality and runtime across step counts']],
   [['想检查 CFG 对伪影的影响','Want to test CFG against artifacts'],['在支持该设置的工具中只改变 CFG','Vary only CFG in a tool that supports it']],
   [['换 Seed 后人物与构图都变化','Identity and composition change after a new seed'],['记录这种可能变化，不假定只是细节变体','Record the possible variation, not merely minor-detail changes']]]),
 },
 '3-4':{
  1:q(['局部修杯子时脸也变了，工具支持蒙版。怎样验证修改范围的影响？','Editing a cup also changes the face; the tool supports masks. How can you test the mask’s effect?'],[['固定其余条件，仅缩小杯子周围蒙版，核对脸与未选区','Fix other conditions, shrink only the mask around the cup, and inspect the face and unselected area'],['换 Seed、模型和参考图后直接归因给蒙版','Change seed, model, and reference, then attribute it to the mask'],['有参考图就不用再检查未选区','A reference image removes the need to inspect unselected areas']],['这是可测试的原因假设，不是保证缩小蒙版就一定解决。','This tests a hypothesis; a smaller mask is not a guaranteed fix.']),
  2:q(['参考图最准确的作用是什么？','What is the most accurate role of a reference image?'],[['提供角色与风格参照，有助于一致性但仍需检查','Provide identity/style guidance, helping consistency while still requiring inspection'],['锁住所有像素，任何编辑都不会变脸','Lock all pixels so identity cannot change'],['自动核实画面中的事实和版权','Automatically verify facts and copyright']],['参考图提供条件，不保证结果或许可。','A reference provides conditioning, not guaranteed output or permission.']),
  7:q(['工具支持 inpaint 时，它主要用于什么？','What is inpainting primarily used for when supported?'],[['在画面内部指定区域生成修改，并检查其他区域是否受影响','Regenerate a designated region inside an image, checking for changes elsewhere'],['在原图边界外新增画布内容','Add canvas content beyond the original bounds'],['把音频自动转成字幕','Automatically transcribe audio']],['局部重绘不是绝对的“不动其他区域”保证。','Local inpainting is not an absolute guarantee that all other areas remain unchanged.']),
  10:q(['节水图中人物保持一致，但手没有碰到水龙头。为检查动作关系，下一轮怎样改？','The character is consistent, but the hand does not reach the tap. How should the next iteration test that relationship?'],[['保留角色与场景，先只修改手与开关的动作描述并核对结果','Preserve character/scene; change only the hand-handle relation in the prompt and inspect'],['同时换角色、角度和画风','Change character, angle, and style together'],['只改字幕说“已经关上”','Change captions to say the tap is already off']],['把要修的问题限定清楚，一轮先改一个可诊断因素。','Define the defect and change one diagnosable factor per iteration.']),
 },
 '3-5':{
  1:q(['前一帧卡片还在手中，下一帧无解释地消失。能直接确认什么？','A card in the hand vanishes in the next frame without explanation. What can you directly establish?'],[['出现物体连续性问题，但具体模型故障原因还需排查','Object continuity failed; the specific model cause still needs investigation'],['一定是字幕时间轴造成','The subtitle timeline must have caused it'],['一定是使用了错误的压缩格式','The compression format must be wrong']],['描述看得见的问题，避免凭一张结果猜内部唯一根因。','Describe the visible failure rather than inventing a unique internal cause.']),
  7:q(['本课要求先写开始、中间、结束三帧。这说明什么？','This lesson asks you to plan beginning, middle, and ending frames. What does that mean?'],[['它是帮助组织短镜头的制作方法，不是所有视频模型的内部机制','It is a shot-planning method, not the internal mechanism of every video model'],['所有视频模型都只生成两张图再线性插值','All video models generate only two images and linearly interpolate'],['写清关键帧就保证无人物漂移','Specifying keyframes guarantees no identity drift']],['实际模型可能用不同的时空生成方法，规划与实现机制应分开。','Models may use different spatiotemporal methods; planning and implementation are distinct.']),
  10:q(['连续两镜拍同一段行走：摄影机从动作轴一侧切到另一侧，人物屏幕运动由向右变向左，却没有交代换位。这属于什么问题？','Two consecutive shots show the same walk. The camera crosses the action axis, reversing screen movement from rightward to leftward without establishing the change. What is the issue?'],[['未交代的越轴可能造成方向混淆，应调整镜位或加入交代镜头','An unestablished axis crossing can confuse direction; adjust camera placement or establish the change'],['只要画面清晰，就不影响空间理解','Sharp images eliminate spatial confusion'],['人物从右侧入画本身就能证明越轴','Entering from the right alone proves an axis crossing']],['这里明确给出了跨轴和方向反转；仅凭入画位置或普通不连续不能判定跳轴。','The scenario explicitly establishes axis crossing and reversed direction; entrance position or generic discontinuity alone would not.']),
  14:m(['本题已指定镜头目的与运动要求，按要求配对，不猜唯一艺术选择。','Match explicit shot requirements, not supposedly unique artistic choices.'],[
   [['证据文字需静止可读，不移动机位','Evidence text must stay readable; camera must not move'],['固定镜头','Locked-off shot']],
   [['保持距离，从左向右展示一排设施','Keep distance; show a row of facilities left to right'],['缓慢横向移动','Slow lateral camera move']],
   [['沿视线后退，让人物在画面变小','Move backward along the viewing direction so the character appears smaller'],['缓慢拉远','Slow pullback']],
   [['一个镜头装不下三项动作，要求拆开','Three actions are too much for one shot; separate them'],['切成多个单动作镜头','Split into multiple single-action shots']]]),
 },
 '3-6':{
  2:q(['你亲耳确认 TTS 把术语读错了，下一步最合理是什么？','You personally confirm that TTS mispronounced a term. What next?'],[['调整工具支持的发音标注或文本，重新生成并亲耳回听','Adjust supported pronunciation hints or text, regenerate, and listen again'],['只要 ASR 输出拼写正确，就不必再听','If ASR spells it correctly, no listening is needed'],['只修改字幕，保留已确认错误的音频','Change captions only, retaining confirmed incorrect speech']],['先确认是声音错误，再修 TTS；ASR 不能代替回听。','Confirm the speech error, then fix TTS; ASR does not replace listening.']),
  6:q(['音乐来源不明，或者已有来源但没有适用本次用途的许可，怎样处理？','Music has an unknown source, or a known source without permission covering this use. What should you do?'],[['取得适用许可，换成已有适用授权的素材，或移除','Obtain suitable permission, replace with material already licensed for this use, or remove it'],['标注网址就等于获得许可','Listing the URL grants permission'],['不收费发布就永远无需许可','Noncommercial posting never requires permission']],['来源、署名和使用许可不同，授权范围要覆盖实际用途。','Source, attribution, and permission are different; the license must cover the actual use.']),
  10:q(['自动字幕把“反射”写成“发射”，但还没听原音。先做什么？','Automatic captions replace “reflection” with “emission,” but you have not heard the original. What first?'],[['对照脚本听原音，区分发音错和转写错，再修对应环节','Listen against the script to distinguish speech from transcription error, then fix the correct stage'],['直接改 TTS 文本，字幕不可能错','Change TTS text immediately; captions cannot be wrong'],['只换声音角色，假定原稿有问题','Change the voice and assume the script is wrong']],['ASR 可误识别正确发音，也可能修正错误发音，所以必须先核对原音。','ASR can mistranscribe correct speech or normalize incorrect speech; inspect the original audio first.']),
  14:m(['把核验动作与它能支持的结论配对。','Match each verification action to the conclusion it supports.'],[
   [['对照原文确认数字、单位和适用范围','Check the number, unit, and scope against its source'],['这条事实有相符的依据','This factual claim has matching evidence']],
   [['许可覆盖本次用途，且已满足署名等条件','License covers this use and attribution conditions are met'],['这些素材具备本次使用的授权依据','These materials have authorization for this use']],
   [['检查并移除未获准使用的个人信息','Inspect and remove personal information not permitted for use'],['已处理发现的未授权隐私内容','Identified unauthorized private content was addressed']],
   [['按适用规则说明 AI 生成或辅助环节','Disclose generated/assisted stages under applicable rules'],['已完成对应的 AI 使用说明','The relevant AI-use disclosure was made']]]),
  15:m(['把误解与修正配对。','Match misconceptions to corrections.'],[
   [['字幕文字对就够','Correct caption text is sufficient'],['还要核对出现时间和阅读速度','Also check timing and reading speed']],
   [['音乐越响越好','Louder music is always better'],['配乐不应盖住要听清的人声','Music should not mask intelligible narration']],
   [['ASR 文本就是原音的绝对证据','ASR text is definitive proof of the original audio'],['它是辅助转写，仍应亲耳核对','It assists transcription; listen to verify']],
   [['知道来源就等于获准使用','Knowing the source grants permission'],['还需确认许可范围和使用条件','Verify license scope and conditions']]]),
 },
 '3-7':{
  1:q(['怎样准确说明本周使用的原理，而不过度概括？','How should you accurately describe this week’s mechanisms?'],[['说明所用图文、图像、视频与音频方法，并区分教学示意和工具实际支持的功能','Explain the methods used, distinguishing teaching simplifications from actual tool features'],['声称所有视频模型都只做关键帧线性插值','Claim every video model only interpolates keyframes linearly'],['只要工具叫 AI，就具有同一生成机制','Every tool called AI has the same mechanism']],['不同模型有不同架构，作品说明应对应实际使用的方法。','Architectures vary; the explanation should match the methods actually used.']),
  5:q(['节水片看完后，同学误以为“关紧水龙头会让水变干净”。怎样改进？','After the water-conservation film, a classmate thinks turning off a tap cleans the water. How should you improve it?'],[['澄清是避免不必要流水，调整误导画面或旁白，再请人复述','Clarify that it avoids wasted flow, revise misleading visuals/narration, and retest understanding'],['只增加更多节水标语，不核对误解','Add slogans without checking the misunderstanding'],['保持原片，认为画面漂亮就足够','Keep it unchanged because it looks good']],['反馈指出具体因果误解，修复也应针对该误解。','The feedback identifies a causal misunderstanding; address that specific misunderstanding.']),
  10:q(['本周最终任务要保存两次有理由的修改。只上传成片但没写修改记录，还应补什么？','The final task asks for two reasoned revisions. A film is uploaded without revision records. What remains to add?'],[['补实际改动、理由与复查结果，不能编造修改经历','Add actual changes, reasons, and rechecks; do not invent a revision history'],['随便写两句“已优化”就够','Two generic “improved” statements suffice'],['重新开始所有作品，已有素材不可用','Restart everything; previous material cannot be reused']],['修改记录帮助理解自己的创作过程，应与真实操作相符。','Revision records help reflection and should match actual work.']),
  13:m(['把节水作品反馈与对应修正配对。','Match feedback on the water-conservation project to a targeted revision.'],[
   [['观众误以为关水可以净水','Viewer thinks turning off water purifies it'],['澄清避免浪费的作用，去掉净水暗示','Clarify waste prevention and remove purification implications']],
   [['观众找不到画面引用的数据来源','Viewer cannot locate a cited number’s source'],['为对应数字补可追溯出处','Add a traceable reference for that number']],
   [['旁白太快，字幕也读不完','Narration and captions are too fast'],['删重复内容并重新核对时长与字幕节奏','Remove repetition and recheck duration and caption pace']],
   [['先显示水已关，再显示伸手去关','Water appears off before the hand reaches to turn it off'],['修正动作先后与镜头衔接','Correct action order and shot continuity']]]),
  15:m(['将发布检查与所需证据配对。','Match release checks to required evidence.'],[
   [['事实检查','Fact check'],['原始来源支持实际表述、数字与范围','Original sources support the actual claim, number, and scope']],
   [['素材许可检查','Material permission check'],['已取得覆盖用途的许可并满足条件','Obtained permission covering the use and complied with its terms']],
   [['隐私检查','Privacy check'],['未暴露未经许可使用的个人信息','No unauthorized use or disclosure of personal information']],
   [['AI 使用说明','AI-use disclosure'],['按适用要求准确说明生成或辅助环节','Accurately disclose generation/assistance under applicable requirements']]]),
 },
};

for (const [key, questions] of Object.entries(MEDIA_COMPLETIONS)) {
 MEDIA_QUESTIONS[key] = {...MEDIA_QUESTIONS[key], ...questions};
}

export const MEDIA_THEORY:Record<string,Bilingual[]>={
 '3-1':[
  ['**本课用一个简化图文模型说明看图**\n一些视觉 Transformer 把图像切成 Patch，再形成视觉表示、经编码和图文连接支持回答。这不是所有图文模型的唯一架构。Patch 大小通常由架构确定，不是成品工具通用的用户按钮。','**A simplified vision-language model**\nSome vision transformers split images into patches, form visual representations, and connect encoded features to language. This is not the only architecture. Patch size is usually an architecture choice, not a universal user control.'],
  ['**切块数量怎么数**\n假设无重叠且能整除：块数=(宽÷Patch边长)×(高÷Patch边长)。224×224、边长16时为196块；边长14时为256块。真实系统还可能裁切、缩放或加入额外 Token。','**Counting patches**\nWith non-overlapping, evenly dividing squares: count=(width/patch side)×(height/patch side).224×224 with side16 gives196; side14 gives256. Real systems may resize, crop, or add extra tokens.'],
  ['**用户能改善什么**\n先保证原图清晰，必要时提供局部裁图，或选择工具支持的细节档位。放大模糊图片不等于恢复不存在的细节。单变量测试要固定模型、问题和其他设置。','**What users can improve**\nSupply clear originals, useful crops, or supported detail settings. Enlarging a blurry image does not restore absent information. Fix model, question, and other settings in a single-variable test.'],
  ['**描述不是事实担保**\n图文对应强不代表每个数字都正确。对照物体、文字、位置和单位；发现错读先描述证据，不猜唯一内部根因。','**Description is not a fact guarantee**\nStrong correspondence does not verify every number. Check objects, text, positions, and units. Describe evidence of an error before hypothesizing internal causes.'],
  ['**今天保留什么**\n保存图片观察记录：AI 回答、原图对应位置、核对结果。明天继续练习区分看得见的证据与推测。','**Today’s record**\nKeep image observations: AI answer, source-image location, and verification result. Tomorrow distinguish visible evidence from inference.'],
 ],
 '3-2':[
  ['**把可见证据与推测分开**\nOCR 读字符；对象识别判断类别；空间理解判断指定视角下的位置；图表理解结合数字、坐标轴与单位。证据不清时应说明不确定，而不是补出没看见的细节。','**Separate visible evidence from inference**\nOCR reads characters; object recognition identifies categories; spatial reasoning uses a stated viewpoint; chart interpretation combines values, axes, and units. When evidence is unclear, state uncertainty instead of inventing details.'],
  ['**先描述错误，再找原因**\n把B2读成82是字符误读，把椅子说成书包是对象误识别。这些现象不能直接证明模型内部哪一层失效；先检查清晰度、遮挡与可见上下文。','**Describe errors before diagnosing causes**\nB2 read as 82 is a character misread; a chair called a backpack is an object error. Neither identifies a failed internal layer. Inspect clarity, occlusion, and visible context first.'],
  ['**位置与数字都有参照**\n说左右时明确观察者与参照物；读图表时核对轴单位、刻度与范围。纵轴为千人、柱值3，就是3000人，不是3人。','**Positions and numbers need references**\nSpecify viewpoint and reference object for left/right. Check chart units, scale, and scope. A bar of 3 on an axis labeled thousands of people means 3,000, not 3.'],
  ['**设计一个小对照**\n同一张文字图做清晰版与模糊版，固定图文工具和问题，各读至少两次并保留所有结果。对照原文核查；结果没变化也有记录价值。裁切或放大可能改变信息，但不保证更准。','**Design a small comparison**\nUse clear and blurred copies of one text image. Fix tool and question; read each at least twice and retain all results. Verify against the source. Unchanged results are informative too; cropping or enlarging does not guarantee accuracy.'],
  ['**保存这次观察**\n留下清晰版与模糊版的读数、核对依据和差异。明天开始创作校园节水插画，把“先看证据再下结论”的习惯用在生成结果检查上。','**Keep this observation**\nRetain clear/blurred readings, verification evidence, and differences. Tomorrow begin a school water-conservation illustration and use evidence-first checking on generated results.'],
 ],
 '3-3':[
  ['**图像生成的一种常见方法**\n扩散模型通过逐步去噪生成图像，有些在压缩的潜空间中进行。不是所有生图工具都采用完全相同的方法。Seed、Steps、CFG 等控件也因工具不同而不同。','**One common image-generation approach**\nDiffusion models generate through progressive denoising, sometimes in a compressed latent space. Image tools do not all use identical methods or expose the same Seed, Steps, or CFG controls.'],
  ['**随机起点不是角色锁**\nSeed 控制随机起点。换 Seed 可能改变构图、身份和细节；同 Seed 还要固定模型版本、尺寸和采样设置，且服务仍可能有不可复现因素。','**A seed is not an identity lock**\nSeed controls the random starting point. Changing it may change composition, identity, and details. Matching seeds also requires matching model/version, dimensions, and sampling settings; service nondeterminism may remain.'],
  ['**参数要看工具支持**\nSteps 控制去噪次数，CFG 是某些模型的引导强度。加大数值不保证更好，过高可能增伪影或耗时。没有控件时，可只改提示中的一个具体要求做对照，并记录工具的随机波动。','**Use supported controls**\nSteps controls denoising iterations; CFG is guidance strength in some models. Higher values do not guarantee better output and may increase artifacts or cost. Without exposed controls, vary one concrete prompt requirement and note random variation.'],
  ['**节水插画实验**\n本日到外部工具创作校园节水插画，固定主题等条件，改变一项可用设置，保存两次结果并上传对比或结果截图。只记录实际观察，不提前宣称哪组一定更好。','**Water-conservation illustration experiment**\nCreate an illustration in an external tool. Fix the topic and other conditions, vary one supported setting, save both results, and upload a comparison or result screenshot. Record actual observations, not a predetermined winner.'],
  ['**收进作品盒**\n保留插画、提示与唯一改动记录。明天在这张图上修改一个区域。','**Keep your work**\nKeep the illustration, prompt, and one-change record. Tomorrow edit one region of this image.'],
 ],
 '3-4':[
  ['**在已有图片上做一次可检查的改动**\n正向提示说明主体和关系；工具支持时，负向提示可以描述希望避免的内容，但不能保证排除。inpaint 修改图内区域，outpaint 扩展边界；使用前先看工具是否提供该功能。','**Make one checkable image edit**\nPositive prompts describe subjects and relations. Supported negative prompts describe undesired content without guaranteeing exclusion. Inpainting edits inside an image; outpainting extends its bounds. First check which controls the tool offers.'],
  ['**参考图提供参照，不是保证**\n它可帮助保持角色和风格，但仍可能漂移。记录必须保留的脸、服装、位置和画风，改完逐项对照，包括未选中的区域。','**References guide, not guarantee**\nA reference can help identity/style consistency, but drift remains possible. List the face, clothing, position, and style to preserve, then inspect all areas after editing.'],
  ['**诊断用对照，不用猜**\n怀疑蒙版太大时，固定其他条件只改范围。若工具不支持蒙版，就用它实际支持的参考图编辑方式并检查整图。不能看到变脸就断言唯一原因。','**Diagnose through comparison**\nTo test an oversized mask, vary only its area. Without mask support, use supported reference editing and inspect the whole result. A changed face does not establish a unique cause.'],
  ['**今天的任务**\n在节水插画上只改一个区域，例如杯子换水壶；保留修改前后版本，上传对比图或结果截图并记录真实变化。','**Today’s task**\nEdit one region of the water-conservation image, such as replacing a cup with a bottle. Save before/after versions, upload a comparison or result screenshot, and record actual changes.'],
  ['**收进作品盒**\n保留原图、修改图、保留项与检查记录。明天把这个场景发展为一个短镜头。','**Keep your work**\nKeep original/edited images, preserved features, and checks. Tomorrow develop this scene into a short shot.'],
 ],
 '3-5':[
  ['**规划短镜头，不假定内部算法**\n本课用开始、中间、结束画面描述动作。这是一种制作计划，不表示所有视频模型都先造关键帧再插值；实际模型可以使用不同的时空生成方法。','**Plan a shot without assuming its algorithm**\nDescribe beginning, middle, and ending states. This is a production plan, not a claim that every video model generates keyframes and interpolates. Models use different spatiotemporal methods.'],
  ['**让动作容易看懂**\n同一学生走近水龙头、伸手、关紧。保持衣服、手、开关位置与光照连贯；动作太复杂就缩短或拆镜。机位靠近主体叫推近，后退叫拉远；横向平移与原地转动的摇摄不同。明确描述有帮助，但不保证不会漂移。','**Make action readable**\nThe same student approaches, reaches, and turns the tap off. Keep clothing, hand, handle, and lighting continuous. Simplify or split overloaded actions. A push-in moves closer; a pullback moves away. Lateral camera translation differs from panning in place. Clear descriptions help but do not guarantee consistency.'],
  ['**空间连续性与越轴**\n180° 动作轴帮助安排机位。未经交代跨到另一侧，可能使屏幕运动方向反转并让人迷惑。普通物体瞬移或入画位置不同，不足以单独证明越轴。','**Spatial continuity and axis crossing**\nThe180-degree action axis helps camera placement. An unestablished crossing can reverse screen direction and confuse viewers. Teleporting props or different entrance positions alone do not prove a crossing.'],
  ['**逐帧检查实际结果**\n本日制作约5秒节水镜头，上传视频或三个时间点截图。检查身份、道具位置、动作顺序；失败时先记录哪里变了，再尝试一个局部修正。','**Inspect the actual frames**\nMake an approximately five-second shot and upload video or screenshots of three moments. Check identity, props, and action order; record failures and try a targeted correction.'],
  ['**收进作品盒**\n保留这一个短镜头与检查记录。明天加旁白，最后一天再组合成15–30秒短片。','**Keep your work**\nKeep this shot and its checks. Add narration tomorrow and assemble the15–30-second film on the final day.'],
 ],
 '3-6':[
  ['**声音和字幕分开核对**\nTTS 把文字变声音，ASR 把声音转写成文字。转写可能出错，也可能自动纠正原音的错词，所以先亲耳听原音，再与脚本和字幕比较。','**Verify speech and captions separately**\nTTS turns text into speech; ASR transcribes speech. Transcription can introduce errors or normalize mistakes, so listen to the original before comparing script and captions.'],
  ['**修对环节**\n原音正确、字幕错误：修字幕；原音读错：改发音标注或文本，再生成回听。旁白太长先删重复内容并试读，不为了塞进镜头而加速到听不懂。','**Fix the correct stage**\nCorrect audio/wrong captions: fix captions. Wrong speech: adjust supported pronunciation or text, regenerate, and listen. Shorten repetition and time narration instead of making it unintelligibly fast.'],
  ['**字幕与混音**\n核对字幕文字、时间点与阅读速度；整体偏移可整体调整后抽查首尾。人声应清楚，配乐不要盖住重点。','**Captions and mixing**\nCheck text, timing, and reading speed. Shift a globally delayed track, then inspect both ends. Keep narration intelligible and music below it.'],
  ['**知道来源还不够**\n音乐、图片、字体和声音素材需具备适用本次用途的许可，并满足署名等条件。可授权不等于已授权。避免暴露未获准的个人信息，按适用要求说明 AI 参与。','**Knowing the source is not enough**\nMusic, images, fonts, and voices need permission covering this use and compliance with conditions such as attribution. Licensable is not licensed. Protect personal information and disclose AI involvement as applicable.'],
  ['**收进作品盒**\n上传节水旁白音频、视频或配音结果截图，保留回听与修改记录。明天组合成15–30秒短片。','**Keep your work**\nUpload narration audio/video or a result screenshot, keeping listening and revision records. Assemble the15–30-second film tomorrow.'],
 ],
 '3-7':[
  ['**把前几天的节水作品组合起来**\n用外部剪辑工具完成15–30秒短片，核心信息清楚，画面与旁白协调。上传成片或能展示完成结果的截图，并保存两次有理由的修改记录。','**Assemble your water-conservation project**\nUse an external editor to finish a15–30-second film with a clear message and coherent visuals/narration. Upload the film or screenshots demonstrating the result and retain two reasoned revisions.'],
  ['**原理说明对应实际方法**\n图文编码、扩散生成、镜头规划与语音/字幕各负责什么？按自己实际使用的方法说明，不把关键帧规划说成所有视频模型的机制。','**Explain the methods actually used**\nWhat did image encoding, image generation, shot planning, and speech/captions each contribute? Describe your actual workflow; do not equate shot planning with every video model’s algorithm.'],
  ['**修改要有具体理由**\n记录现象→原因假设与证据→一次改动→复查。假设未验证就不能写成定论。可先请人复述核心信息，针对真实误解修正。','**Give specific reasons for revisions**\nRecord symptom → hypothesis/evidence → change → recheck. An untested hypothesis is not a proven cause. Ask someone to restate the message and address observed misunderstandings.'],
  ['**发布前另做检查**\n完成学习任务不等于已经取得对外发布许可。核对事实、授权范围、隐私、字幕与适用的 AI 说明要求；问题未解决前不要公开。','**Check separately before publishing**\nCompleting a learning task does not grant publication rights. Verify facts, license scope, privacy, captions, and applicable AI-disclosure requirements before public release.'],
  ['**本周收束**\n保存短片结果、修改理由和素材许可记录。能看懂、听清楚，并能解释怎样改进，是下一次创作的基础。','**Week wrap-up**\nKeep the film result, revision reasons, and permission records. Readability, intelligibility, and explaining improvements prepare you for the next project.'],
 ],
};
export const MEDIA_LABS:Record<string,Both>={
 '3-5':[0,1].map(lang=>({type:'interactive',interactiveKind:'sequence',interactiveTitle:lang?'Make a checkable short shot':'制作可检查的短镜头',interactiveInstruction:lang?'The shot shows one student turning off a tap. Arrange the production and checking stages by dependency.':'镜头表现同一学生关水龙头。按依赖顺序安排制作与检查，不是在猜模型内部算法。',interactiveSequence:lang?['Plan the subject, action, and beginning/middle/end states','Generate or edit the shot from that plan','Compare the produced frames against the plan','Record defects and choose a targeted revision','Apply the revision and recheck continuity']:['确定主体、动作与开始/中间/结束状态','按计划生成或剪辑镜头','把生成画面与计划逐帧对照','记录问题并选定针对性修改','完成修改后再次检查连续性']})) as Both,
 '3-7':[0,1].map(lang=>({type:'interactive',interactiveKind:'diagnose',interactiveTitle:lang?'Check the water-conservation film':'检查节水短片',interactiveInstruction:lang?'Select the records showing a problem; leave the valid record unselected.':'选出存在问题的记录，不要选正常记录。',interactiveItems:[
  {label:lang?'Narration claims closing a tap purifies dirty water.':'旁白说拧紧水龙头能把脏水净化。',detail:lang?'Closing the tap avoids wasted flow; it does not purify water. Correct the claim and check supporting visuals.':'关紧水龙头避免水白流，不是净化水。修正文案并核对画面是否也造成误解。',correct:true},
  {label:lang?'A music URL is recorded, but permission for this use is unknown.':'记录了音乐网址，但不确定是否允许本次使用。',detail:lang?'A source URL is not permission. Obtain suitable rights or replace/remove the track before publication.':'来源网址不等于许可，发布前取得适用许可或替换、移除。',correct:true},
  {label:lang?'The student’s unapproved face appears in the published-work draft.':'准备公开的成片中出现未获准使用的同学面孔。',detail:lang?'Resolve consent and privacy before publication.':'先解决肖像使用许可与隐私问题，再考虑公开。',correct:true},
  {label:lang?'A viewer correctly describes closing the tap to prevent wasted flow.':'观众能正确复述关紧水龙头是为了避免水白流。',detail:lang?'This supports comprehension; it is not a defect or proof that every other check passed.':'这是理解效果的证据，不是缺陷，也不代表其他检查自动通过。',correct:false},
 ]})) as Both,
 '3-4':[0,1].map(lang=>({type:'interactive',interactiveKind:'diagnose',interactiveTitle:lang?'Inspect image-editing records':'检查改图记录',interactiveInstruction:lang?'Select records showing a defect or a comparison problem. Leave the valid record unselected.':'选出存在画面问题或对照方法问题的记录，不要选正常记录。',interactiveItems:[
  {label:lang?'Only the cup should change, but the face changes too.':'只要求改杯子，结果人物脸也变化了。',detail:lang?'Preservation failed. Compare mask extent and supported reference controls from a fixed baseline; this observation alone does not identify a unique cause.':'保留项未满足。可从固定基线检查蒙版范围与参考设置，不能单凭现象确定唯一根因。',correct:true},
  {label:lang?'Framing, color temperature, and background all change; the record attributes the result only to framing.':'同时改景别、色温和背景，却把结果只归因于景别。',detail:lang?'Several factors changed; test them separately before attributing the result.':'多个因素同时变化，应逐项对照后再判断。',correct:true},
  {label:lang?'After a shadow edit, the unselected sky changes from blue to orange.':'修改阴影后，未选中的天空从蓝色变成橙色。',detail:lang?'An unintended region changed. Inspect edit mode, mask, and prompts one at a time and recheck the whole image.':'未要求修改的区域发生变化，逐项检查编辑方式、范围与提示，并核对整图。',correct:true},
  {label:lang?'A reference is attached; before/after images and each change are recorded.':'提供参考图，并保留前后图与每次修改记录。',detail:lang?'This is valid recordkeeping; it helps inspect drift rather than guaranteeing none.':'这是合理记录，有助于检查漂移，但不代表一定不会漂移。',correct:false},
 ]})) as Both,
 '3-3':[0,1].map(lang=>({type:'interactive',interactiveKind:'compare',interactiveTitle:lang?'Design a Steps comparison':'设计 Steps 对照实验',interactiveInstruction:lang?'Your tool supports these controls. You want to test only the effect of Steps. Which design fits?':'工具支持以下控件。你只想检查 Steps 的影响，哪种设计符合目标？',interactiveItems:[
  {label:lang?'Fix model, prompt, dimensions, Seed and CFG; vary only Steps20/30/40.':'固定模型、提示、尺寸、Seed、CFG，只改 Steps20/30/40。',detail:lang?'Only the factor of interest changes. Compare both quality and time.':'只改变要研究的变量，同时比较质量和耗时。',correct:true},
  {label:lang?'Fix Steps and vary CFG4/6/8.':'固定 Steps，改 CFG4/6/8。',detail:lang?'A controlled comparison, but it tests CFG, not Steps.':'是单变量对照，但研究的是 CFG，不是 Steps。',correct:false},
  {label:lang?'Fix Steps and change Seed42/99/314.':'固定 Steps，改 Seed42/99/314。',detail:lang?'It tests seed variation, not the effect of Steps.':'研究随机起点变体，不是 Steps 的影响。',correct:false},
  {label:lang?'Change Steps, prompt and model together.':'同时改变 Steps、提示与模型。',detail:lang?'Multiple factors prevent attributing the difference to Steps.':'多个因素变化，不能把差异归因给 Steps。',correct:false},
 ]})) as Both,
 '3-6':[0,1].map(lang=>({type:'interactive',interactiveKind:'sequence',interactiveTitle:lang?'Verify narration and captions':'核对旁白与字幕',interactiveInstruction:lang?'Confirm script permissions and privacy before generation or upload, then listen and check the result.':'生成或上传前先确认脚本、素材许可与隐私，再回听和终检。',interactiveSequence:lang?['Finalize a short script and confirm permissions and privacy','Generate TTS or record your voice','Listen to the original and correct speech errors','Compare ASR captions and correct transcription/timing','Recheck mixing, captions, and conditions for using the final work']:['确定简短脚本，确认素材许可与隐私','生成 TTS 或录制自己的声音','亲耳回听原音，修正发音问题','对照自动字幕，修正转写与时间轴','终检混音、字幕与成片使用条件']})) as Both,
};
