import type {Bilingual} from './course-fix-builders';
// Explanations for retained questions, indexed by assessment ordinal, not page position.
export const RETAINED_EXPLANATIONS:Record<string,Record<number,Bilingual>>={
 '1-1':{
  1:['图灵测试关注文字交谈中能否分辨机器与人，不是计算速度测试，也不能单独证明意识。','The Turing Test concerns distinguishing a machine from a person through conversation, not calculation speed or proof of consciousness.'],
  3:['专家系统把领域知识主要写成规则；从大量样本学习规律是机器学习的典型路线。','Expert systems primarily encode domain knowledge as rules; learning patterns from examples characterizes machine learning.'],
  5:['深蓝是国际象棋系统；AlphaGo处理围棋。区分它们解决的任务，不把两次里程碑混在一起。','Deep Blue played chess; AlphaGo played Go. Distinguish the tasks rather than conflating the milestones.'],
  7:['AlphaGo把神经网络学习与搜索结合，展示了处理复杂围棋决策的能力；它并未取消搜索。','AlphaGo combined neural-network learning and search for complex Go decisions; it did not eliminate search.'],
  8:['Transformer以注意力机制为核心组织信息，是许多后来的语言模型的基础，不同于专家规则或卷积网络路线。','Transformers organize information through attention and underpin many later language models, unlike expert-rule or convolutional approaches.'],
 14:['GPT是Generative Pre-trained Transformer的缩写，T指模型架构，不是图灵测试。','GPT expands to Generative Pre-trained Transformer; T names the architecture, not the Turing Test.'],
 },
 '1-2':{
  1:['Token是词表中的离散单元，可能对应整词、子词、字符或字节片段，不能统一按汉字或空格计数。','A token is a discrete vocabulary unit that may represent a word, subword, character, or byte fragment; character or space counts are not universal token counts.'],
  2:['Tokenizer先把文本切分为Token并映射为词表编号。注意力权重和下一词元概率由模型后续计算产生，不是分词器的输出。','A tokenizer splits text into tokens and maps them to vocabulary IDs. Attention weights and next-token probabilities are produced by later model computations, not by the tokenizer.'],
  4:['本课BPE每轮统计当前相邻对并合并最高频组合；合并后要重新统计，且不能跨训练片段边界。','Each BPE round counts current adjacent pairs and merges a most-frequent pair. Recount afterward without crossing training-segment boundaries.'],
  9:['上下文窗口限制一次处理的Token容量；词表是可用Token的集合，温度是采样控制。','A context window limits the tokens processed together; a vocabulary lists tokens and temperature controls sampling.'],
 },
 '1-3':{
  1:['编号只是索引，编号相邻不代表向量方向或语义接近。','IDs are indexes; adjacent numbers do not establish similar vector direction or meaning.'],
  2:['Embedding提供可计算的数值表示，不是一条已核实的事实或自然语言释义。','An embedding supplies a numerical representation, not a verified fact or natural-language definition.'],
  4:['有序的一串数构成向量；其中每个数不一定是概率，也不一定对应可命名的含义。','An ordered list of numbers forms a vector; entries need not be probabilities or individually interpretable concepts.'],
  5:['更多维度可能增加表示容量，同时增加存储与计算需求；准确性仍要实际评测。','More dimensions can increase representational capacity and resource use; accuracy still requires evaluation.'],
  7:['对非零向量，余弦相似度把长度归一化后比较方向，所以长度差异本身不会让同方向相似度变低。','For nonzero vectors, cosine similarity normalizes magnitude and compares direction; different lengths alone do not lower similarity for aligned directions.'],
  8:['余弦主要衡量非零向量的夹角关系；词表编号和字符数量不能代替这个计算。','Cosine measures the angular relationship of nonzero vectors; vocabulary IDs and character counts do not substitute for it.'],
 },
 '1-4':{
  1:['同一个静态词元向量本身没有当前句子的具体线索，后续上下文处理才能区分此处词义。','A static token vector lacks the current sentence’s particular clues; contextual processing distinguishes the sense in use.'],
  2:['注意力按当前位置与上下文的关系组合信息；关注什么与信息是否真实是不同问题。','Attention combines information according to contextual relevance; attending to information does not establish its truth.'],
  5:['Q与K的匹配分帮助判断哪些位置更相关，再用权重组合V；这一步不是直接挑选输出Token，也不是把权重解码成文字。','Query-key scores indicate which positions are relevant before weighting values. This step neither directly chooses an output token nor decodes attention weights into text.'],
  9:['Softmax把分数归一化成非负、合计为1的权重。这里的权重不是可信度评分。','Softmax normalizes scores into nonnegative weights summing to one; these are not truth-confidence scores.'],
 12:['不同头可在不同表示子空间捕捉关系，不必重复同一种处理；它们不是已验证的事实来源，也不保证每个头都有固定可命名的职责。','Heads can capture relationships in different representation subspaces rather than all repeating the same processing. They are not verified factual sources, and each need not have a fixed human-readable role.'],
 },
 '1-5':{
  1:['Logits是归一化前的候选分数，不必在0到1之间，也不是已核实的事实。','Logits are unnormalized candidate scores; they need not lie between zero and one and are not verified facts.'],
  3:['完整Softmax分布的总和为1；显示成整数百分比时还要处理舍入。','A complete Softmax distribution sums to one; integer percentage displays also need rounding treatment.'],
  4:['对同一组非相同分数，降低正温度通常让分布更集中；并不会增加模型知识。','For the same unequal scores, lowering positive temperature usually concentrates the distribution; it does not add knowledge.'],
  7:['贪心每步选当前最大分候选。按概率采样允许较低分候选出现，两者不是同一策略。','Greedy decoding chooses a highest-scoring candidate each step; probabilistic sampling can select lower-scoring candidates.'],
  8:['Top-k限制候选集合，不是一口气输出k个Token，也不是从第k名以后开始选。','Top-k restricts the candidate set; it neither emits k tokens at once nor starts selecting below rank k.'],
  9:['Top-p按排序后的累计概率决定集合大小；Top-k按数量截取。候选保留后通常需重新归一化再采样。','Top-p uses cumulative probability to choose set size; top-k uses a count. Retained candidates are usually renormalized before sampling.'],
 },
 '1-7':{
  1:['文字先切分并编号，随后形成向量表示；Softmax在后续分数归一化阶段，不核实输入事实。','Text is segmented and indexed before vector representation; Softmax normalizes later scores and does not verify input facts.'],
  2:['Token ID只标识词表项，Embedding把它映射到可用于神经网络计算的向量。','A token ID identifies a vocabulary entry; an embedding maps it to a vector for neural-network computation.'],
  3:['Attention根据上下文组合相关信息，但信息可能错误或不足，不能因此保证没有幻觉。','Attention combines contextually relevant information that may be wrong or incomplete, so it does not guarantee hallucination-free output.'],
  5:['Softmax将候选分数变为非负且合计为1的分布；Tokenizer与RAG分别负责其他过程。','Softmax converts candidate scores to a nonnegative distribution summing to one; tokenization and RAG serve different functions.'],
  6:['温度与Top-p调整候选分布或候选集合，不是在重新切词或训练模型。','Temperature and top-p adjust the candidate distribution or set, not tokenization or training.'],
  8:['这是可能的上下文使用问题，要检查输入是否被截断及关键要求是否被利用，不能单凭遗漏确定根因。','This may concern context use; inspect truncation and use of key requirements rather than declaring a unique cause from an omission.'],
 10:['高温通常让分布较平坦，低概率候选更可能被采到；这不改变Embedding维度或BPE词表。','Higher temperature usually flattens the distribution, making lower-probability candidates more likely without changing embedding dimensions or BPE vocabulary.'],
 11:['稳定地重复错误仍然是错误。输出一致说明一致性，不提供事实证据。','A consistently repeated error is still wrong; output agreement does not supply factual evidence.'],
 12:['自回归生成把已经生成的内容作为后续条件，逐步继续，而不是一次决定全部文字。','Autoregressive generation conditions later output on what has already been generated rather than deciding the whole text at once.'],
 13:['这是语言生成的简化主链；真实模型还包含多层计算与其他处理，温度等设置作用于相应采样阶段。','This is a simplified generation chain; real models add layers and processing, with controls such as temperature applied at the relevant sampling stage.'],
 14:['资料、工具与核验互补。低温只能改变输出分布，长提示本身也不能保证事实正确。','Evidence, tools, and verification complement each other; low temperature or a long prompt alone cannot guarantee truth.'],
 },
 '2-1':{
  1:['完整例子写明要做什么、面向谁、具体限制和输出结构，减少了需要模型自行猜测的部分。','The complete example specifies task, audience, constraints, and output structure, reducing guesswork.'],
  2:['场合与听众已有知识是背景；“分成三点”才是输出组织方式。','The occasion and audience’s prior knowledge are context; organizing into three points is an output format.'],
  3:['要点数量与每点长度直接约束输出形态，同时也是可检查要求；这里按它在句中的主要作用分类。','Point count and length constrain output shape and are also checkable requirements; this question classifies their primary role.'],
  5:['年级与是否读过原书影响哪些内容要解释；仅限定篇幅或语气并不能补足听众背景。','Grade and familiarity with the book affect needed explanations; length or tone alone does not supply audience context.'],
  6:['这是内容边界，要求不要把没发生的阅读经历写成事实，不是输出排版。','This is a content constraint against inventing reading experience, not a formatting instruction.'],
  8:['“有意思”可作为偏好，但需要例子、受众或具体标准才能让双方判断是否达到。','Interesting can express a preference, but examples, audience, or specific criteria are needed to judge success.'],
 11:['视角、题材、篇幅与交付范围具体，生成结果更容易与任务逐项对照。','Perspective, genre, length, and deliverable scope make results easier to compare against the task.'],
 12:['目标描述要完成的工作；背景解释情境，输出形式规定交付怎样组织。','The goal names the work; context explains the situation, and output format specifies organization.'],
 13:['主题、听众、时间与结构会影响实际内容；重复强调认真并没有增加这些必要信息。','Topic, audience, duration, and structure shape content; repeated requests to be careful add none of these details.'],
 14:['明确三项且不重复，每项结构一致，便于分工和检查，不必让组员再猜如何拆分。','Three distinct items with a common structure support allocation and checking without requiring the group to infer a split.'],
 },
 '2-6':{
  1:['每轮先改变一个可诊断因素并留记录，才能更清楚地判断改动的影响。','Changing one diagnosable factor and keeping records makes effects easier to interpret.'],
  2:['先把失败描述成可观察问题，如超长或缺来源，再决定怎样改。','Describe an observable failure, such as excess length or a missing source, before deciding on a change.'],
  5:['同任务比较字数并检查信息完整性，避免只是把必要内容删掉就称为改善。','Compare length on the same task and check completeness so removing necessary information is not mistaken for improvement.'],
  7:['多项规则同时增加会混杂效果，还可能冲突；问题不是编号或一个固定的规则数量上限。','Adding many rules at once confounds effects and may introduce conflicts; numbering or a universal rule-count limit is not the issue.'],
 10:['保留已验证有效的约束，再针对标题提出单项变化，并回归检查原先的字数要求。','Keep effective constraints, change the title requirement, and recheck the earlier length constraint.'],
 13:['同输入、同标准更可比，但生成仍可能有随机波动，因此应保留并比较实际输出。','The same inputs and rubric improve comparability, but generation can still vary; retain and compare actual outputs.'],
 14:['结果更好并不能说明哪项改动起作用，需控制其他条件进一步比较。','A better result does not reveal which change helped; compare with other factors controlled.'],
 },
 '2-7':{
  1:['长期配置适合约定身份、行为方式与边界；具体作业内容属于当次任务，不应要求无关个人信息。','Persistent configuration suits role, behavior, and boundaries; a particular assignment belongs to the current task, without unnecessary personal data.'],
  4:['本课伙伴以帮助学习为目标，先了解尝试再给提示或同类例子，不替交作业。','This learning partner is designed to understand the learner’s attempt and give hints or analogous examples rather than submit work for them.'],
  5:['这是本课伙伴的帮助边界，应同时说明允许提供哪些帮助，而不是只写禁止。','This is the partner’s assistance boundary; also describe allowed help rather than giving only prohibitions.'],
  7:['可以举清楚标明的虚构例子，但不能把未知或编造内容当作可靠资料。','Clearly labeled hypothetical examples are allowed; unknown or invented material must not be presented as reliable evidence.'],
  8:['先确认卡点再给适量提示，并等待尝试，能保留学习者自己的思考与练习。','Identify the sticking point, offer an appropriate hint, and await an attempt to preserve the learner’s own reasoning and practice.'],
 11:['反馈针对学生实际尝试，说明有效步骤与下一步，而不是直接替换成完整可提交答案。','Feedback responds to the learner’s actual attempt with useful steps and next actions rather than replacing it with a submission-ready answer.'],
 12:['进行中的测验不应由伙伴代答；可以帮助学习通用方法，或在测验后练习相似题。','The partner should not answer an active assessment on the learner’s behalf; general methods and later analogous practice can support learning.'],
 14:['边界应明确且可测试，并配可允许的替代帮助。标题或分隔符本身并不会建立系统权限。','Make boundaries explicit and testable with allowed alternatives; headings or delimiters do not themselves establish system authority.'],
 },
 '4-3':{
  1:['只开放查资料和起草实际需要的工具；联系人、支付或整设备访问与介绍卡任务无关。','Enable only tools needed for research and drafting; contacts, payments, or whole-device access are unrelated to the card.'],
  2:['优先使用有明确机构、日期与可追溯依据的资料，但官方页面也要核对年份与适用范围。','Prefer attributable, dated institutional sources, while still checking year and scope even for official pages.'],
  3:['只读限制可执行的动作，最小范围限制能读哪些文件；两者都不意味着长期记忆或编辑权。','Read-only limits actions and scoped access limits files; neither implies long-term memory or edit permission.'],
  4:['只读也会暴露信息；是否修改联系人不是关键，任务不需要就不应申请访问。','Read-only access still exposes information; lack of modification does not justify unrelated access.'],
  5:['小规模允许资料能测试参数、来源和停止行为，不需要用真实发布来检验这类边界。','Small approved samples can test parameters, sources, and stopping without requiring a real publication.'],
  6:['查看与公开是不同权限；署名、来源是学校或不改原文件都不能替代公开授权。','Reading and publishing are different permissions; attribution, school origin, or leaving the original unchanged does not grant publication rights.'],
  7:['工具最小化让功能范围与任务相称，并不是越通用、越多越好。','Tool minimization matches capability to the task rather than maximizing available functions.'],
  8:['只读允许查看而不允许编辑；对外分享仍是独立权限。','Read-only permits viewing, not editing; external sharing is a separate permission.'],
  9:['可追溯来源更便于核查，但有作者或网址也不保证每个结论正确。','Traceable sources support verification, but an author or URL does not guarantee every claim.'],
 10:['选定照片足以完成任务时，不应访问整相册；承诺不描述私人照片并不减少已经发生的访问。','When selected photos suffice, full-library access is unnecessary; promising not to describe private photos does not undo access.'],
 },
 '4-4':{
  1:['在关键依赖完成后检查，可尽早发现来源问题，再在交付前检查成果要求。','Checking after key dependencies catches source problems early and verifies deliverable criteria before handoff.'],
  2:['替代来源也必须在许可范围内并重新核对内容，不能用标题或无关旧资料补出事实。','Alternative sources must remain permitted and be verified; titles or unrelated old material cannot fill factual gaps.'],
  4:['文件名或大小相近不能证明可删除；本课要求先交付候选与证据，由负责人确认。','Similar names or sizes do not establish safe deletion; this course requires handing over candidates and evidence for confirmation.'],
  5:['先看日期差异是否来自版本或适用范围，无法解决时保留冲突并报告。','Check whether versions or scope explain date differences; preserve and report unresolved conflicts.'],
  6:['可交接记录应包含做过什么、具体卡点、是否产生外部效果和下一步，不只是笼统评价。','A handoff needs actions taken, specific blockers, external effects, and next steps rather than vague assessments.'],
  7:['检查点把结果与约定条件对照，再决定继续、修改或停止，不等于发布或普通保存。','A checkpoint compares results to agreed criteria before continuing, revising, or stopping; it is not publication or mere storage.'],
  8:['上限要明确计数口径：首次之后的额外重试，和包含首次的总尝试次数不同。','Define the counting convention: additional retries differ from total attempts including the initial call.'],
  9:['恢复需记录错误、保持权限和预算，再检查替代路径结果，不是隐藏故障。','Recovery records errors, preserves permission and budget, and verifies alternatives instead of hiding failures.'],
 10:['任务遇到未获准的信息需求，应停下调整范围；猜测或临时读取同样跨越权限。','An unauthorized information requirement calls for stopping and revising scope; guessing or temporary access still crosses the boundary.'],
 },
 '4-5':{
  1:['经同意的非敏感偏好可以限时保存；位置路线、他人电话与完整聊天会扩大不必要的收集。','Consented non-sensitive preferences can be retained for a limited period; routes, others’ numbers, or full chats expand unnecessary collection.'],
  2:['一次任务的数量要求不代表长期偏好，任务结束按约定停止使用并清理。','A task-specific count is not a lasting preference; stop using and clean it up as agreed after the task.'],
  3:['查看、修改和删除让用户能控制保存内容，而不是只能接受隐藏的记录。','View, edit, and delete controls give users control rather than forcing acceptance of hidden records.'],
  4:['用途和期限共同限制复用，不应因数据还在就拿去服务无关新任务。','Purpose and lifetime both constrain reuse; retained data should not automatically serve unrelated tasks.'],
  5:['应停止使用并实际执行删除，核对结果后如实反馈；隐藏记录不等于删除。','Stop using and actually delete the record, then verify and report the result; hiding is not deletion.'],
  6:['保存与任务相关且获同意的少量偏好，不因为可能方便就永久保存全部数据。','Retain a small set of relevant, consented preferences rather than everything indefinitely for possible convenience.'],
  7:['临时记忆服务当前任务，期限和清理规则应提前明确，不自动升级成长期偏好。','Temporary memory serves the current task with defined lifetime and cleanup rather than becoming a lasting preference automatically.'],
  8:['可查看强调透明，仍应配合修改、删除与用途说明，并不代表公开给其他人。','Visibility means transparency to the user, alongside editing, deletion, and purpose information—not public disclosure.'],
  9:['最小化先判断必要性和授权，再决定保存哪些字段及多久。','Minimization checks necessity and authorization before choosing fields and retention.'],
 10:['这个偏好任务不需要住址，应停止使用并清除无关信息，核实实际结果；其他偏好也需同意。','This preference task does not need an address; stop use and remove it with verified results. Other preferences still require consent.'],
 },
 '4-6':{
  1:['配置既要有执行路径，也要有检查和停止机制；仅列工具或角色不足以约束行动。','Configuration needs execution, checking, and stopping; tools or a role alone do not constrain action.'],
  2:['指定材料限制证据范围，“不发送”限制外部动作，两者都不是永久记忆或界面风格。','Named materials limit evidence and no-sending limits external action; neither specifies memory or visual style.'],
  3:['缺资料测试检验系统能否承认未知并走停止或补问分支，而非为完成率编造依据。','Missing-data tests check acknowledgment of uncertainty and stop/clarification paths rather than invented evidence.'],
  4:['当前草稿任务不授予自动发送权；先核对当前正文与受众并取得对应确认，不能转交另一个Agent绕过限制。','A draft-only task does not grant automatic sending; verify content and audience and obtain applicable confirmation, without delegating around the restriction.'],
  5:['修复资料范围约束，并把越界案例加入复测；多加网站或改标题不修复越权根因。','Fix source-scope enforcement and retest the violating case; extra sources or title changes do not fix the permission fault.'],
  6:['通过当前测试需要同时满足成果、证据与边界条件，不是只看速度、篇幅或引用数量。','Passing the current test requires output, evidence, and boundary conditions together, not speed, length, or citation count alone.'],
 10:['数量与格式合格不能弥补来源越界，应修正访问限制并重新测试。','Meeting count or format does not offset a source-scope violation; correct access restrictions and retest.'],
 },
 '4-7':{
  1:['成品要用具体配置与测试记录展示规则，而不是靠工具多、数据多或声称全自动来证明可靠。','A project demonstrates rules through concrete configuration and tests, not tool count, data volume, or claims of full automation.'],
  2:['说明书让接手者理解能做什么、依据什么、遇到何种情况停下，以及谁负责确认。','A guide explains capabilities, evidence, stopping conditions, and responsibility for confirmation.'],
  3:['缺失资料需要明确指出，不把猜测写成已完成的事实；后续补充仍须符合原授权。','Identify missing evidence rather than present guesses as completed facts; later additions must respect permission.'],
  5:['限定公开资料并只交付草稿，风险和检查范围都更可控；公开可读仍不等于任意再发布许可。','A public-source, draft-only task has manageable scope and risk; public readability still does not grant unrestricted republication rights.'],
  6:['公开前核对内容、署名、素材许可与受众，按本课规则由人决定；预测点击量不能替代授权。','Check content, attribution, rights, and audience before human approval under this course’s rules; predicted clicks do not replace authorization.'],
  9:['失败恢复需要有限预算与退出路径，否则同一问题会反复消耗资源。','Recovery needs a bounded budget and exit path or the same failure can consume resources indefinitely.'],
 10:['记忆范围应按同意、必要性和期限限制，并提供管理方式；隐藏保存内容不等于尊重控制权。','Limit memory by consent, necessity, and lifetime with management controls; hidden storage does not respect user control.'],
 },
};
