import {q,f,m,type Both,type Bilingual} from './course-fix-builders';
export const LEARNING_QUESTIONS:Record<string,Record<number,Both>>={
 '1-6':{
  1:q(['预训练主要做什么？','What is the main role of pretraining?'],[['从大量样本中学习可泛化的模式并更新参数','Learn generalizable patterns from many examples by updating parameters'],['针对当前问题检索最新网页而不更新参数','Retrieve current webpages for a question without updating parameters'],['只改变回答的采样温度','Change only response sampling temperature']],['训练会更新参数；检索与采样设置是不同过程。','Training updates parameters; retrieval and sampling controls are different processes.']),
  2:q(['微调与只在提示中提供示例有什么主要区别？','How does fine-tuning differ from adding examples only in a prompt?'],[['微调继续训练并更新参数；提示示例通常只影响本次上下文','Fine-tuning trains and updates parameters; prompt examples usually affect the current context'],['两者都会在每次提问时重新做完整预训练','Both repeat full pretraining for each question'],['提示示例永久改写参数，微调只修改聊天记录','Prompt examples permanently update parameters; fine-tuning changes only chat history']],['上下文学习可改变当次表现，不代表现场训练参数。','In-context examples can change current behavior without online parameter training.']),
  3:q(['对齐工作的目标更接近哪项？','Which best describes an alignment objective?'],[['改善模型遵循指令、偏好与行为边界的方式','Improve instruction following, preferences, and behavioral boundaries'],['实时补齐世界上所有新事实','Add every new fact worldwide in real time'],['只减少回答使用的Token数量','Only reduce the token count of answers']],['对齐可以包含训练等多种方法，但不保证事实全知或永远正确。','Alignment can use training and other methods; it does not guarantee omniscience or correctness.']),
  4:f(['利用已有参数与当前上下文生成回答，叫___。','Generating with existing parameters and the current context is called ___.'],[['推理','inference'],['预训练','pretraining'],['数据标注','data labeling']],['本课的推理指模型运行生成输出，不是重新训练，也不专指逻辑推理题。','Inference here means running the model, not retraining or only solving logical reasoning tasks.']),
  5:m(['按描述配对，不把几种方法当作互斥的固定阶段。','Match the descriptions; these methods are not mutually exclusive fixed stages.'],[
   [['预训练','Pretraining'],['在广泛数据上学习一般模式','Learn general patterns from broad data']],
   [['微调','Fine-tuning'],['在已有模型上继续训练','Continue training an existing model']],
   [['对齐','Alignment'],['让行为更符合目标指令、偏好与边界','Bring behavior closer to intended instructions, preferences, and boundaries']],
   [['推理','Inference'],['运行已有模型处理当前输入','Run an existing model on current input']]]),
  6:q(['模型把一部虚构书及作者当真实文献引用。确认该书不存在后，应如何归类？','A model cites a fictional book and author as a real source. Once nonexistence is established, how should this be classified?'],[['事实性幻觉：把编造内容当作真实依据','A factual hallucination: invented content presented as evidence'],['格式错误：只要调整引用格式就可信','A formatting error fixed by changing citation style'],['明确标注的创意写作','Clearly labeled creative fiction']],['创作虚构书本身不是问题；把它声称为真实文献才是这里的错误。','Inventing a book for fiction is different from presenting it as a real reference.']),
  7:q(['为什么不能仅凭回答流畅就相信它？','Why is fluency alone insufficient evidence of truth?'],[['生成合理语言与核实具体事实是不同能力','Plausible language generation and fact verification are different abilities'],['流畅表达意味着模型刚检索过网页','Fluency means the model just searched the web'],['句子越短越不会包含错误','Shorter sentences cannot contain errors']],['来源、日期与具体内容要单独核对；表达风格并不说明核查已发生。','Check sources, dates, and claims separately; style does not establish verification.']),
  8:q(['要回答今天刚发布的政策内容，哪种做法合适？','How should you answer about a policy released today?'],[['查发布机构的最新原文，核对日期与适用范围','Check the issuing body’s current text, date, and scope'],['引用模型记住的旧政策，默认今天没变','Use remembered old policy and assume no change'],['多问几次，取出现最多的版本','Ask repeatedly and take the most frequent version']],['多数输出可能重复同一旧信息，不能代替最新来源。','Repeated outputs may share stale information; agreement does not replace a current source.']),
  9:q(['要核对378×492，哪种方法提供更直接的计算依据？','Which provides direct calculation evidence for 378×492?'],[['用计算器或代码计算，并检查输入与运算符','Use a calculator or code and inspect operands and operator'],['让模型用更肯定的语气重复答案','Ask the model to repeat more confidently'],['挑一个长度合适的数字作为估计值','Choose a number of plausible length as the exact result']],['工具也可能被输错参数；正确输入的结果为185976。','Tools can receive wrong inputs too; the correct product is 185976.']),
 10:m(['把明确的任务与主要核验方式配对。','Match specified tasks to primary verification methods.'],[
   [['核对今天北京气温','Verify today’s Beijing temperature'],['最新天气来源及地点、时间','Current weather source with location and time']],
   [['核对精确乘法结果','Verify an exact multiplication'],['计算器或代码与输入检查','Calculator or code with input checks']],
   [['核对校内图书借阅期限','Verify the school borrowing period'],['获准使用的现行原始规则','The current authorized original rules']],
   [['选择三个虚构故事开头','Choose three fictional story openings'],['按主题、新意与可读性比较','Compare theme fit, originality, and readability']]]),
 11:f(['RAG，即检索增强生成，先___相关材料，再把材料提供给模型生成回答。','RAG, retrieval-augmented generation, first ___ relevant material, then supplies it to the model.'],[['检索','retrieves'],['微调','fine-tunes'],['采样','samples']],['检索找出相关片段，生成基于片段作答；这通常不需要改模型参数。','Retrieval finds relevant passages for generation, usually without changing model parameters.']),
 12:q(['带有RAG引用的回答为什么仍需核对？','Why should a RAG answer with citations still be checked?'],[['来源可能有误、检索可能遗漏，回答也可能误读片段','Sources may be wrong, retrieval may omit evidence, and generation may misread it'],['只要有来源链接，正文就已自动验证','A source link automatically verifies the answer'],['只要文档够多，相关段落必定都被使用','Enough documents guarantee that all relevant passages were used']],['应逐条检查引用是否真实支持结论，以及是否遗漏条件。','Check whether each citation supports the claim and whether conditions were omitted.']),
 13:q(['回答忠实引用了一份已经过期的规定。问题一定只是模型编造吗？','An answer faithfully quotes an expired rule. Is the issue necessarily fabrication?'],[['不一定，来源时效与适用范围也出了问题','No; source currency and applicability are also problems'],['一定，任何错误都只发生在生成环节','Yes; all errors arise only during generation'],['没有问题，忠实引用就等于当前有效','No issue; faithful quotation means current validity']],['忠实于旧资料不等于符合现在事实，应查来源链而不只调整温度。','Faithfulness to old material is not current accuracy; inspect the source chain, not just temperature.']),
 14:q(['怎样比较直接回答与RAG回答的效果？','How should direct generation and RAG be compared?'],[['使用同一组问题和评分标准，核对事实、引用与遗漏条件','Use the same questions and rubric; verify facts, citations, and missing conditions'],['RAG只测简单问题，直接回答只测难题','Test RAG only on easy questions and direct generation on hard ones'],['只按答案长短与专业语气排名','Rank only by length and professional tone']],['保持评测条件可比，并记录失败样本；引用数量本身不是质量分。','Keep conditions comparable and retain failures; citation count alone is not a quality score.']),
 },
};
export const LEARNING_THEORY:Record<string,Bilingual[]>={
 '1-5':[
  ['**候选词的原始分数**\n模型根据当前上下文，为下一位置的候选 Token 计算原始分数 Logits。分数可以为正或负，它们表示生成偏好，不是事实正确率。','**Raw candidate scores**\nThe model computes raw scores, or logits, for candidate tokens at the next position using the current context. Scores can be positive or negative. They express generation preferences, not factual accuracy.'],
  ['**先调温度，再换成概率**\n标准温度采样先把 Logits 除以正温度 T，再做 Softmax，得到非负、总和为 1 的概率。图中的整数百分比经过舍入分配，合计仍为 100%。','**Temperature before probabilities**\nStandard temperature sampling divides logits by a positive temperature T before applying Softmax. The resulting probabilities are nonnegative and sum to one. The chart allocates rounded integer percentages so they still total 100%.'],
  ['**温度改变分布，不增加知识**\n对同一组不完全相同的分数，较低的正温度让高分候选更突出，较高温度让分布更平缓。这里的旋钮使用一组固定示例分布，通过等价的概率幂变换演示效果，不是实时调用模型。温度不保证事实正确，也不保证两次输出一定相同或不同。','**Temperature changes the distribution, not knowledge**\nFor fixed, unequal scores, a lower positive temperature concentrates probability on higher scores; a higher temperature flattens the distribution. This control demonstrates the equivalent probability-power transformation of a fixed example distribution rather than a live model call. Temperature guarantees neither truth nor identical or different outputs.'],
  ['**缩小候选池，再选择**\nTop-k 保留排名最高的 k 个候选；Top-p 按概率从高到低累加，保留达到阈值的候选，因此数量可以变化。截取后重新归一化，再按概率采样。Greedy 则直接选最高分候选，与按概率抽取不同。','**Filter candidates, then choose**\nTop-k retains the k highest-ranked candidates. Top-p accumulates candidates in descending probability order until reaching its threshold, so the count can vary. Renormalize after filtering, then sample. Greedy decoding instead selects the highest-scoring candidate directly.'],
  ['**Day 5 完成**\n你已经串起 Logits ÷ Temperature → Softmax → Top-k/Top-p → 重新归一化 → Sampling。模型选出的下一块文字仍需结合任务核验。明天看训练、推理与幻觉的区别。','**Day 5 complete**\nYou have connected logits ÷ temperature → Softmax → Top-k/Top-p → renormalization → sampling. The selected text still needs checks appropriate to the task. Tomorrow, compare training, inference, and hallucination.'],
 ],
 '1-7':[
  ['**文字进入模型**\nTokenizer 将输入切成 Token 并映射为编号，Embedding 把编号变成向量。这是后续计算的起点；编号相近不代表意思相近。','**Text enters the model**\nThe tokenizer splits input into tokens and maps them to IDs; embeddings map IDs to vectors. These are inputs to later computation. Nearby IDs do not imply similar meanings.'],
  ['**结合上下文**\nTransformer 用注意力等多层计算处理表示。Q 与 K 的匹配决定如何加权汇总 V，位置信息帮助区分先后顺序。这个简化流程不是模型内部全部计算，也不能仅凭一句错误回答就确定哪个注意力头出了问题。','**Use the context**\nA Transformer processes representations through layers containing attention and other computations. Q–K matching determines how Values are weighted; position information helps distinguish order. This simplified flow is not the entire computation, and a wrong answer alone cannot identify a faulty attention head.'],
  ['**选择下一块文字**\n输出层产生 Logits。采用标准温度采样时，先除以正温度 T，再用 Softmax 转成概率；按 Top-k/Top-p 截取候选后重新归一化并采样。选出的 Token 加入已有内容，继续下一轮。','**Choose the next token**\nThe output layer produces logits. With standard temperature sampling, divide by a positive T before Softmax; after Top-k/Top-p filtering, renormalize and sample. Append the selected token to the existing text and repeat.'],
  ['**从可观察的问题开始核验**\n答非所问时核对输入和上下文；引用时核对来源是否存在、是否支持结论；计算时核对运算和输入。补充证据可以帮助改善回答，但这些检查不等于已经定位模型内部的唯一故障。','**Start with observable failures**\nFor an off-topic answer, inspect the input and context. For a citation, check that the source exists and supports the claim. For arithmetic, check operands and operations. Evidence can improve an answer, but these checks do not establish a unique internal model fault.'],
  ['**Week 1 通关**\n保留你的文字流程和三条核验记录：词元、向量、上下文处理、候选分数、概率与采样。生成机制解释文字怎样出现，证据帮助判断内容是否可信。下周学习把任务、资料、示例和检查标准写清楚。','**Week 1 complete**\nKeep your written flow and three verification notes: tokens, vectors, context processing, candidate scores, probabilities, and sampling. Generation explains how text appears; evidence helps assess its reliability. Next week, write clear tasks, materials, examples, and checks.'],
 ],
 '1-6':[
  ['**模型怎样学，与怎样回答**\n预训练在广泛数据上学习模式；微调是在已有模型上继续训练；对齐旨在改善指令遵循、偏好与行为边界，也可能通过微调等方法实现。它们不是完全互斥的步骤，也不把模型变成实时事实数据库。','**Learning versus answering**\nPretraining learns patterns from broad data. Fine-tuning continues training an existing model. Alignment aims to improve instruction following, preferences, and behavioral boundaries and may use fine-tuning. These are not mutually exclusive stages or a guarantee of current facts.'],
  ['**推理不等于重新训练**\n本课“推理”指利用已有参数和当前上下文运行模型、生成输出，不专指解逻辑题。提示中给例子通常改变当次上下文，不会当场重新预训练参数。','**Inference is not retraining**\nInference means running existing parameters on current context to generate output, not only solving logic problems. Prompt examples usually affect the current context rather than retraining parameters on the spot.'],
  ['**流畅不等于真实**\n模型可能把不存在的书、错误日期或假引文写得很自然。虚构故事允许创作，但事实问题要有相应证据；语言的肯定程度不是事实核查结果。','**Fluency is not truth**\nA model can fluently invent books, dates, or quotations. Fiction permits invention, but factual questions require evidence. Confident language is not a fact-check result.'],
  ['**先取证据，再生成**\nRAG（Retrieval-Augmented Generation，检索增强生成）先检索相关材料，再把片段与问题交给模型作答。它可用获准的内部资料；最新政策先查原始发布来源，精确运算用计算器或代码。检索也可能遗漏或找到过期资料，仍要核对来源、引用、输入和结果。','**Retrieve evidence, then generate**\nRAG means retrieval-augmented generation: retrieve relevant passages, then supply them with the question to the model. It can use authorized internal material. Check current policies at their original source and exact arithmetic with calculators or code. Retrieval can miss evidence or return stale sources, so verify sources, citations, inputs, and results.'],
  ['**选择合适的核验方式**\n保存天气、计算与故事三项任务的工具选择和核验记录。明天把分词、表示、注意力与生成过程串起来，区分生成得出与证据支持。','**Choose appropriate checks**\nKeep tool choices and verification notes for weather, arithmetic, and stories. Tomorrow connect tokenization, representations, attention, and generation while distinguishing generated answers from supported facts.'],
 ],
};
