import type { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. When looking at an unfamiliar image, what is the most reliable first step?', options: ['Write what is directly visible in the picture', 'Guess what the photographer wanted to express', 'Judge the character\'s personality first', 'Invent what happened outside the frame'], correct: 0 },
  { type: 'quiz', question: '2. Which sentence is an observation, not an interpretation?', options: ['The boy is probably lost', 'There is an open blue book on the right side of the desk', 'The dark sky means everyone is sad', 'This classroom just finished an exam'], correct: 1 },
  { type: 'quiz', question: '3. A faraway sign is blurry in the image. How should you record it?', options: ['Write the text that looks closest', 'Ask AI to guess multiple times and pick the majority', 'Mark it as unconfirmed and note where it is blurry', 'Ignore blur and treat it as clear text'], correct: 2 },
  { type: 'quiz', question: '4. AI says “This photo was taken in winter,” but the picture only shows coats. Correct judgment?', options: ['Coats are enough proof of winter', 'This is only a possible interpretation; still need date/location evidence', 'AI vision conclusions can be used directly', 'Coats have nothing to do with season at all'], correct: 1 },
  { type: 'quiz', question: '5. Why can cropped images cause wrong judgments?', options: ['Cropping always changes pixel colors', 'Cropping automatically creates fake objects', 'Context around the scene may be removed', 'Cropped images are always fake'], correct: 2 },
  { type: 'quiz', question: '6. If you want to use an image in a knowledge short, what check matters most?', options: ['Only check if it looks pretty', 'Ensure observations match script facts, and verify source and usage permission', 'Ask AI to invent a more dramatic story', 'If there is no text, it is always safe to use'], correct: 1 },
  { type: 'fill', question: '7. “There is a bright Moon in the upper-left corner” is a visible ___.', parts: ['This sentence is a visible', '___', '.'], options: ['observation', 'interpretation', 'guess'], correct: 'observation' },
  { type: 'fill', question: '8. “This may be around a lunar eclipse” should be labeled as ___.', parts: ['This sentence should be labeled as a', '___', '.'], options: ['possible interpretation', 'confirmed fact', 'text from image'], correct: 'possible interpretation' },
  { type: 'fill', question: '9. For details you cannot confirm from one image, record the ___.', parts: ['You should record the', '___', '.'], options: ['uncertainty', 'standard answer', 'story ending'], correct: 'uncertainty' },
  { type: 'quiz', question: '10. There is a cup with a few drops nearby. Which statement is most accurate?', options: ['The cup was just taken from a fridge', 'The water must leak from the cup', 'Visible drops are next to the cup; the cause cannot be confirmed from this image'], correct: 2 },
  { type: 'practice', task: '11. [Image Observation Card] Choose one image with clear source and no privacy issues. For your D1 story, write an observation card with at least 3 visible details, 1 possible interpretation, 2 uncertainties, and which line of your script it supports.', rubric: 'Must clearly separate observation, interpretation, and uncertainty; include at least three observations, one interpretation using words like “may,” and two unconfirmed points; connect accurately to your script line. Do not write guesses as facts.', placeholder: 'Image source: ...\nVisible details: 1. ... 2. ... 3. ...\nPossible interpretation: ...\nUncertainties: 1. ... 2. ...\nSupported script line: ...', minLength: 70, referenceAnswer: 'Image source: a photo I took of a Moon model. Visible details: a gray sphere at center; a white beam from the right; the left side is darker. Possible interpretation: the bright-dark contrast may come from right-side lighting. Uncertainties: model material cannot be confirmed from the photo alone; real Moon size is not provable from this image. Supported script line: lighting creates bright and dark sides on a sphere.' },
  { type: 'match', question: '12. Match: observation, interpretation, uncertainty', pairs: [{ left: 'A gray sphere is in the center', right: 'Observation' }, { left: 'It may represent the Moon', right: 'Interpretation' }, { left: 'Shooting location cannot be confirmed', right: 'Uncertainty' }, { left: 'Image comes from a museum public page', right: 'Source information' }] },
  { type: 'match', question: '13. Match: visual factors and risks', pairs: [{ left: 'Very few pixels in far text', right: 'Text may be read incorrectly' }, { left: 'Wide-angle lens close to subject', right: 'Proportions may be exaggerated' }, { left: 'Strong shadows on edges', right: 'Shape may be misread' }, { left: 'Only one corner is cropped out', right: 'Context may be missing' }] },
  { type: 'match', question: '14. Match: actions after finding a problem', pairs: [{ left: 'AI sees an object that is not in the original image', right: 'Recheck original image and delete false description' }, { left: 'Date appears only in caption text', right: 'Verify it from the original source' }, { left: 'Detail is too blurry', right: 'Mark unconfirmed or switch to clearer image' }, { left: 'Image license is unclear', right: 'Do not use it yet; find usable material' }] },
  { type: 'match', question: '15. Match: observation card sections', pairs: [{ left: 'Three directly visible details', right: 'Visible details' }, { left: 'Reason statement with “may”', right: 'Possible interpretation' }, { left: 'Questions one image cannot answer', right: 'Uncertainties' }, { left: 'One line mapped to D1 script', right: 'Script connection' }] },
];

export const v3enw3d2Data: DayContent = {
  day: 2,
  title: 'Multimodal Diagnosis: OCR, Objects, Spatial Reasoning, Charts, and Visual Hallucinations',
  shards: 30,
  steps: [
    { type: 'theory', content: '👁️ **Opening | Five Image Understanding Abilities**\nToday we split image understanding into OCR, object recognition, spatial relations, chart reading, and visual hallucinations. Goal: separate “what is seen” from “what is imagined.”' },
    { type: 'video', url: '', content: 'Video placeholder: how one image moves from observation to careful interpretation' },
    { type: 'theory', content: '🔍 **Theory Card 1 | OCR and Object Recognition**\nOCR can fail under blur, tilt, or occlusion. Object recognition can misclassify similar outlines as common objects.' },
    { type: 'theory', content: '🧩 **Theory Card 2 | Spatial and Chart Understanding**\nLeft-right, front-back, and occlusion relationships are frequent error points. Chart errors often come from wrong axes or units.' },
    { type: 'theory', content: '🌫️ **Theory Card 3 | Visual Hallucinations**\nWhen evidence is weak, models may auto-complete with learned patterns and produce believable mistakes. Low-confidence regions should be explicitly marked as uncertain.' },
    ...graded,
    { type: 'theory', content: '✅ **Wrap-up | Observation Card Complete**\nYou now have source info, at least three visible details, one possible interpretation, two uncertainties, and a mapped D1 script line. Tomorrow we turn reliable clues into a key visual.' },
  ],
};
