import { DayContent } from '../../types';

export const w2d5Data: DayContent = {
  day: 5,
  title: "JSON 与输出控制",
  shards: 1,
  steps: [
    { type: 'theory', content: "🔧 **今日主题：让 AI 变成可编程的零件**\n\n写文章、聊天时 AI 可以自由发挥。但当你需要把 AI 的输出**接入程序**时，它必须严格按照你要求的格式输出。\n\n今天学习：如何让 AI 输出稳定的 **JSON、表格、CSV** 等结构化格式。" },
    { type: 'video', url: "", content: "视频：让 AI 乖乖输出 JSON —— 从自由文本到结构化数据" },
    { type: 'theory', content: "📋 **第一章：为什么需要结构化输出？**\n\n| 自由文本输出 | 结构化输出 |\n|------|------|\n| 「这个产品很好，评分 4.5」 | `{\"product\": \"X\", \"rating\": 4.5, \"sentiment\": \"positive\"}` |\n\n自由文本只能人读，结构化输出可以被**程序直接解析**：\n- 存入数据库\n- 传给下一个 API\n- 生成图表\n- 触发自动化流程" },
    { type: 'theory', content: "🎯 **第二章：让 AI 输出 JSON 的 5 个技巧**\n\n1. **给出完整模板**：在 Prompt 中展示你期望的 JSON 结构\n2. **说明每个字段**：字段含义、类型（string/number/boolean）、枚举值\n3. **用 Few-Shot**：给 1-2 个完整的输入→JSON 输出示例\n4. **加约束**：「只输出 JSON，不要输出其他解释文字」\n5. **使用 JSON Mode**：部分 API（如 OpenAI）支持 `response_format: { type: 'json_object' }`" },
    { type: 'theory', content: "📊 **第三章：其他结构化格式**\n\n| 格式 | 适用场景 | Prompt 写法 |\n|------|----------|-------------|\n| **Markdown 表格** | 对比分析、特征矩阵 | 「用 Markdown 表格展示，列：名称/价格/评分」 |\n| **CSV** | 批量数据，导入 Excel | 「以 CSV 格式输出，第一行是表头」 |\n| **YAML** | 配置文件 | 「以 YAML 格式输出」 |\n| **XML** | 遗留系统集成 | 「以 XML 格式输出，根节点为 <results>」 |" },
    { type: 'theory', content: "🔒 **第四章：约束输出内容**\n\n除了格式，还需要约束**内容**：\n\n| 约束类型 | Prompt 写法 |\n|----------|-------------|\n| 枚举约束 | sentiment 只能是 positive/negative/neutral |\n| 范围约束 | rating 必须是 1-5 的整数 |\n| 必填约束 | 所有字段不能为空 |\n| 长度约束 | summary 不超过 50 字 |\n| 类型约束 | price 必须是数字类型，不能是字符串 |" },
    { type: 'theory', content: "📏 **第五章：控制输出长度**\n\n| 方法 | Prompt 写法 | 效果 |\n|------|-------------|------|\n| 字数限制 | 不超过 200 字 | 粗略控制 |\n| 要点限制 | 列出 3 个要点 | 控制条目数 |\n| Token 限制 | max_tokens=500（API 参数） | 硬性截断 |\n| 格式限制 | 用一条推文总结 | 隐式限制 |\n\n⚠️ 注意：`max_tokens` 是**硬截断**——到了上限会直接断句。建议在 Prompt 中设软限制，`max_tokens` 只做保底。" },
    { type: 'theory', content: "🧪 **第六章：Function Calling（函数调用）**\n\n高级格式控制的终极方案：**Function Calling**。\n\nOpenAI 等 API 支持你定义一个「函数签名」（参数名、类型、描述），AI 会严格按照这个签名返回参数——**连 JSON Schema 都帮你验证了**。\n\n```json\n{\n  \"name\": \"analyze_review\",\n  \"parameters\": {\n    \"sentiment\": { \"type\": \"string\", \"enum\": [\"positive\", \"negative\", \"neutral\"] },\n    \"score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 5 }\n  }\n}\n```\n\nAI 的输出会被强制约束在这个 Schema 内。" },
    { type: 'quiz', question: "1. 【价值】结构化输出（如 JSON）相比自由文本的最大优势是？", options: ["字数更少", "可以被程序直接解析和处理，接入自动化流水线", "AI 生成更快"], correct: 1 },
    { type: 'quiz', question: "2. 【场景】你需要让 AI 批量分析 1000 条评论的情感。输出应该用什么格式？", options: ["一段自然语言描述", "JSON 数组，每条包含 id、text、sentiment 字段", "纯数字列表"], correct: 1 },
    { type: 'fill', question: "3. 【API】OpenAI API 中强制 AI 输出合法 JSON 的参数叫 response_format，类型设为 ___。", parts: ["response_format 的类型设为", "___", "即可强制输出 JSON。"], options: ["json_object", "text", "markdown"], correct: "json_object" },
    { type: 'quiz', question: "4. 【技巧】以下哪种 Prompt 最能确保 AI 输出合法 JSON？", options: ["请输出 JSON", "请严格按照以下 JSON 模板输出，不要添加任何解释文字：\n{\"name\": \"string\", \"age\": \"number\", \"city\": \"string\"}", "用代码格式输出"], correct: 1 },
    { type: 'quiz', question: "5. 【Debug】AI 输出了 JSON，但在 JSON 前面加了一句「以下是结果：」，导致你的程序解析失败。怎么修？", options: ["在程序里手动去掉前面的文字", "在 Prompt 中明确加上「只输出 JSON 对象本身，不要包含任何其他文字或解释」", "换一个模型"], correct: 1 },
    { type: 'match', question: "6. 【连线】不同输出格式的最佳场景", pairs: [{ left: "JSON", right: "接入前端/后端程序 API" }, { left: "Markdown 表格", right: "在文档中直观对比" }, { left: "CSV", right: "批量导入 Excel 或数据库" }, { left: "YAML", right: "生成配置文件" }] },
    { type: 'practice', task: "【把自然语言改成 JSON 输出要求】把下面这段需求改写成一个要求 AI 输出 JSON 的 Prompt，并定义至少 3 个字段：\n\n「请帮我从一段餐厅评论中提取菜品名、评分、是否推荐。」", rubric: "是否明确要求 JSON 输出（且只输出 JSON）；是否定义了至少 3 个字段；字段类型是否清晰（字符串 / 数字 / 布尔）；是否说明字段缺失时怎么处理。", placeholder: "请按下面的 JSON 格式输出，只返回 JSON：\n{\n  \"字段 1\": ...,\n  \"字段 2\": ...\n}\n说明：...", minLength: 80, referenceAnswer: "请从下面的餐厅评论中提取信息，只返回符合格式的 JSON，不要任何解释文字。\n\n格式：\n{\n  \"dish_name\": \"<字符串：菜品名，没有则用 unknown>\",\n  \"rating\": <0-5 整数：评分，没有则用 0>,\n  \"recommend\": <true 或 false：是否推荐>,\n  \"reason\": \"<字符串：一句话原因，最多 30 字>\"\n}\n\n说明：\n- 字符串如有引号请转义\n- 评分必须是数字，不能写 “4 星”\n- 如果评论里没有明确推荐，请按 false 处理\n\n评论原文：..." },
    { type: 'practice', task: "【去掉解释性文字】下面是一个返回带解释的 Prompt：\n\n「请把下面这段评论分类为「正面 / 负面 / 中性」，并解释你的判断理由。」\n\n请你改写它，让 AI 只返回纯 JSON（包含 label 和 confidence），方便程序解析。", rubric: "是否要求只输出 JSON、不输出解释；是否定义了清晰字段（如 label / confidence）；是否说明 label 的取值集合；是否考虑“无法判断”的情况。", placeholder: "请只返回 JSON，不要解释：\n{\n  \"label\": \"正面\" | \"负面\" | \"中性\",\n  ...\n}", minLength: 60, referenceAnswer: "请只返回 JSON，不要任何解释、Markdown 或前后多余文字。\n\n格式：\n{\n  \"label\": \"<只能是 positive / negative / neutral / unknown 中的一个>\",\n  \"confidence\": <0-1 之间的小数，保留 2 位>,\n  \"evidence\": \"<字符串：评论中支持判断的关键词，最多 20 字>\"\n}\n\n说明：\n- 如果评论看不出明显倾向，请使用 unknown，不要硬猜\n- confidence 反映你对判断的把握程度\n\n评论：..." },
    { type: 'practice', task: "【设计你自己的 JSON 提取任务】挑一个你真实想自动化的小任务（如：从招聘 JD 里提取关键信息、从订单短信里提取金额和店家），写出对应的 JSON 提取 Prompt。", rubric: "是否选了真实场景；是否定义了至少 3 个字段；是否处理“信息缺失”的情况；是否要求纯 JSON；是否能直接给 AI 使用。", placeholder: "场景：...\n\n请只返回 JSON：\n{\n  \"字段 1\": ...,\n  \"字段 2\": ...\n}", minLength: 100, referenceAnswer: "场景：从招聘 JD 里提取关键信息，方便我快速比较多个岗位。\n\n请只返回 JSON，不要任何解释或 Markdown：\n{\n  \"company\": \"<公司名，未提及则 unknown>\",\n  \"title\": \"<职位名>\",\n  \"location\": \"<城市，未提及则 unknown>\",\n  \"salary_min\": <月薪下限，单位元，未提及则 0>,\n  \"salary_max\": <月薪上限，单位元，未提及则 0>,\n  \"skills\": [\"<技能 1>\", \"<技能 2>\"],\n  \"remote_friendly\": <true 或 false>\n}\n\n说明：\n- 不能编造未提到的信息，缺失字段使用上面规定的默认值。\n- skills 至多列 5 个最关键的硬技能，不要列“沟通能力”这类软技能。\n\nJD 原文：..." },
    { type: 'practice', task: "【综合大题】请写一份完整的「用户反馈结构化提取」Prompt，准备给后端程序直接调用。要求：\n1) 明确指令和角色；\n2) 完整的 JSON Schema（至少 5 个字段，包含字符串 / 数字 / 布尔 / 数组各一种）；\n3) 字段缺失时的默认值约定；\n4) “只返回 JSON”的强约束；\n5) 一段示例输入和示例输出，证明 AI 能照做。", rubric: "是否覆盖 5 项；JSON 结构是否合理且字段类型多样；是否处理缺失值；是否给出清晰的输入输出示例；是否能直接接到程序里用。", placeholder: "## 指令\n你是...\n\n## JSON 输出格式\n{\n  \"字段 1\": ...\n}\n\n## 缺失值约定\n- ...\n\n## 示例\n输入：...\n输出：{...}", minLength: 240, referenceAnswer: "## 指令\n你是用户反馈结构化提取助手。请阅读用户反馈原文，按下面的 Schema 输出 JSON，只返回 JSON 对象，不要任何说明文字、Markdown 或代码块包裹。\n\n## JSON 输出格式\n{\n  \"feedback_id\": \"<字符串，原文中提到的工单号或 unknown>\",\n  \"category\": \"<只能是 bug / feature / praise / complaint / other 中的一个>\",\n  \"severity\": <1-5 整数，5 表示严重影响使用>,\n  \"is_blocking\": <true 或 false，是否阻断用户当前操作>,\n  \"tags\": [\"<相关功能标签 1>\", \"<标签 2>\"],\n  \"summary\": \"<一句话总结，最多 30 字>\"\n}\n\n## 缺失值约定\n- 字符串字段缺失：使用 \"unknown\"\n- 数字字段缺失：使用 0\n- 数组字段缺失：使用 []\n- 布尔字段缺失：使用 false\n- 不允许编造原文未提及的信息\n\n## 示例\n输入：用户工单 #20245：今天上午用 App 想付款，一直转圈最后报错 503，重试 5 次都失败。\n输出：\n{\n  \"feedback_id\": \"20245\",\n  \"category\": \"bug\",\n  \"severity\": 5,\n  \"is_blocking\": true,\n  \"tags\": [\"payment\", \"network\"],\n  \"summary\": \"支付页持续 503 报错，无法完成付款\"\n}\n\n反馈原文：..." },
    { type: 'theory', content: "🎉 **Day 5 完成！**\n\n你已经掌握了让 AI 按格式输出的全套工具。从此 AI 不再只是聊天工具，而是**可编程的数据处理单元**。\n\n**Day 6 预告**：咒语越强大，被滥用的风险越大。明天学习 **防御术 —— Jailbreak、Prompt Injection 与安全防护**。" }
  ]
};
