import { DayContent } from '../../../types';

export const v3enw1d2Data: DayContent = {
  day: 2,
  title: 'Word Block Factory: Token, Tokenizer, and BPE',
  shards: 1,
  steps: [
    { type: 'theory', content: 'Chapter 1: Models do not read full sentences first. We see a sentence, but the model first sees a sequence of IDs. A tokenizer cuts text into tokens, then maps each token to an ID in its vocabulary. A token might be one character, one whole word, or part of a word, so it is not always one letter or one Chinese character.' },
    { type: 'video', url: '', content: 'Animation: how one mixed Chinese-English sentence is split by a tokenizer into word blocks and IDs' },
    { type: 'quiz', question: '1. Which statement about a token is most accurate?', options: ['A token is always one Chinese character', 'A token is a discrete text unit the model uses for processing', 'Tokens exist only in English'], correct: 1 },
    { type: 'quiz', question: '2. What does a tokenizer mainly do before model computation starts?', options: ['Checks whether each sentence is factually true', 'Splits text into tokens and maps them to IDs', 'Translates all languages into English'], correct: 1 },
    { type: 'quiz', question: '3. Why can\'t we estimate token count only by counting characters?', options: ['Different models, languages, and content can be split differently', 'A tokenizer randomly deletes half the text', 'Every token always contains exactly ten characters'], correct: 0 },
    { type: 'theory', content: 'Chapter 2: BPE works like building with common blocks. If every rare word gets its own vocabulary slot, the vocabulary becomes huge. If we always split into single characters, sequences become long. The BPE idea is to start with small pieces, count frequent neighboring pieces, and merge common pairs. For example, if "artificial" and "intelligence" often appear as a pair in training data, that pair may become a common block.' },
    { type: 'fill', question: '4. BPE prefers to ___ high-frequency pieces that often appear next to each other.', parts: ['BPE prefers to', '___', 'high-frequency neighboring pieces.'], options: ['merge', 'delete', 'translate'], correct: 'merge' },
    { type: 'quiz', question: '5. Why does BPE balance vocabulary size and sequence length?', options: ['A huge vocabulary costs resources, but over-fragmented splitting creates longer token sequences', 'A smaller vocabulary always guarantees better factual accuracy', 'Longer sequences always make a model faster'], correct: 0 },
    { type: 'match', question: '6. Match each text type to a likely tokenization behavior.', pairs: [{ left: 'Common English words', right: 'May become one token or a few subwords' }, { left: 'Rare personal names', right: 'May be split into several smaller pieces' }, { left: 'Mixed Chinese-English sentence', right: 'Different language parts may use different granularity' }, { left: 'Code and symbols', right: 'Punctuation, indentation, and fragments also take tokens' }] },
    { type: 'theory', content: 'Chapter 3: The same sentence can be split in different ways. Chinese has no natural spaces, English has roots and suffixes, and numbers, emoji, and code each behave differently. Different model tokenizers may split the same sentence into different token counts. Different splitting does not automatically mean one model is smarter, but it does affect context capacity, speed, and cost.' },
    { type: 'quiz', question: '7. The word unbelievable may be split as un + believ + able. What does this show?', options: ['Tokenizers can use subword pieces to handle less common words', 'Models cannot process whole words', 'English can only be processed letter by letter'], correct: 0 },
    { type: 'quiz', question: '8. Why should Chinese, English, and code not all be split by spaces only?', options: ['Chinese usually has no word spaces, and code includes many symbols and structures', 'English never has spaces', 'Code does not need tokenization'], correct: 0 },
    { type: 'fill', question: '9. The maximum number of tokens a model can handle at once is called the context ___.', parts: ['The token limit is called the context', '___', '.'], options: ['window', 'dictionary', 'temperature'], correct: 'window' },
    { type: 'theory', content: 'Chapter 4: Tokens are also your budget. A context window is like a limited desk: system rules, chat history, user input, and model output all take space. More tokens usually mean more compute time and cost. Good optimization is not only making text shorter. Keep information truly needed for the task, and leave room for output.' },
    { type: 'quiz', question: '10. If only 800 tokens remain in the context window, but you paste about 1500 tokens of material, what is most likely?', options: ['The model automatically gets a larger window', 'Some content may be truncated, or there may be too little room left for output', 'The tokenizer compresses all tokens into one for free'], correct: 1 },
    { type: 'quiz', question: '11. Which method is more reasonable for reducing token usage?', options: ['Remove repeated and irrelevant content while keeping task-critical evidence', 'Delete all task requirements and keep only background text', 'Repeat the same instruction five times'], correct: 0 },
    { type: 'quiz', question: '12. Two models process the same Chinese text: one uses 120 tokens, the other 160. What can we conclude directly?', options: ['The first one is definitely smarter', 'The second one is definitely more accurate', 'Only that their tokenization or vocabulary may differ; capability needs separate testing'], correct: 2 },
    { type: 'match', question: '13. Match each token-budget situation to its effect.', pairs: [{ left: 'Very long input material', right: 'Uses more context space' }, { left: 'Keeping repeated chat logs', right: 'Wastes token budget' }, { left: 'Extracting only relevant passages first', right: 'Makes the input more focused' }, { left: 'Need a long-form answer', right: 'Reserve output capacity in advance' }] },
    { type: 'quiz', question: '14. What is the best way to compare two tokenizers fairly?', options: ['Use the same multilingual samples with numbers and code, then record splits and token counts', 'Give each tokenizer completely different articles', 'Only compare which product name is more popular'], correct: 0 },
    { type: 'practice', task: '15. BPE Block Experiment: Given these training phrases: "artificial intelligence", "manual review", "intelligent assistant", "smart devices". First list repeated characters or neighboring chunks, then propose two merge rounds and explain how those merges could change token counts.', rubric: 'A strong answer identifies repeated or high-frequency neighboring chunks, gives two evidence-based merge rounds, and explains that merging frequent chunks can reduce token counts for related text. It does not need to exactly match a real production vocabulary.', placeholder: 'Frequent chunks: ...\nRound 1 merge: ...\nRound 2 merge: ...\nEffect on token count: ...', minLength: 60, referenceAnswer: 'Repeated chunks include pieces around "intelli-" and "smart"-related patterns in these phrases. In round 1, you might merge a frequent pair like "intelli" + "gence"; in round 2, merge another frequent pair from assistant/device contexts. After merging, common phrases can be represented with fewer tokens. Real BPE decisions still depend on full-corpus frequencies.' },
    { type: 'theory', content: 'Day 2 complete. You have seen the first processing stage before text reaches model reasoning: tokenization, vocabulary IDs, and BPE merging of common chunks. Tomorrow these IDs enter embeddings and become vectors in a semantic map.' }
  ]
};
