import { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. What mainly happens during pretraining?', options: ['The model learns language and patterns from massive data', 'The model permanently stores every user chat', 'The model verifies internet facts one by one'], correct: 0 },
  { type: 'quiz', question: '2. Fine-tuning is most like which process?', options: ['Continuing training on the base model for specific tasks or behaviors', 'Lowering temperature settings', 'Clearing the vocabulary before every prompt'], correct: 0 },
  { type: 'quiz', question: '3. What is the main goal of alignment training?', options: ['Make model behavior better follow human instructions, safety, and preferences', 'Guarantee knowledge of all future news', 'Remove tokenization'], correct: 0 },
  { type: 'fill', question: '4. After a user sends a prompt, the stage where the model actually generates an answer is called ___.', parts: ['This stage is called', '___', '.'], options: ['inference', 'pretraining', 'annotation'], correct: 'inference' },
  { type: 'match', question: '5. Match each stage with its role in model growth.', pairs: [{ left: 'Pretraining', right: 'Learn general patterns from massive data' }, { left: 'Fine-tuning', right: 'Continue training for specific tasks' }, { left: 'Alignment', right: 'Improve instruction following and behavior boundaries' }, { left: 'Inference', right: 'Generate output step by step from current input' }] },
  { type: 'quiz', question: '6. The model gives a non-existent book title and full author name. What is this?', options: ['A hallucination: content that sounds plausible but lacks evidence', 'A tokenizer error', 'A normal citation that needs no checking'], correct: 0 },
  { type: 'quiz', question: '7. Why does fluent language not equal factual correctness?', options: ['Training optimizes plausible continuation, not automatic verification of every fact', 'Fluent writing always comes from a search engine', 'Facts depend only on sentence length'], correct: 0 },
  { type: 'quiz', question: '8. For a policy announced today, what should you do first?', options: ['Retrieve authoritative up-to-date sources and mark the date', 'Increase temperature', 'Ask the model to guess from training memory'], correct: 0 },
  { type: 'quiz', question: '9. For calculating 378×492, which method is more reliable?', options: ['Use a calculator tool and check the inputs', 'Ask the model to do confident mental math', 'Increase top-p'], correct: 0 },
  { type: 'match', question: '10. Match each question type with a verification tool.', pairs: [{ left: 'Latest news', right: 'Authoritative retrieval with date checking' }, { left: 'Exact arithmetic', right: 'Calculator or code execution' }, { left: 'School policy', right: 'Approved original documents' }, { left: 'Creative story', right: 'Human judgment against goals' }] },
  { type: 'fill', question: '11. The core idea of RAG is to first ___ relevant passages from external sources, then answer.', parts: ['First', '___', 'relevant passages.'], options: ['retrieve', 'invent', 'delete'], correct: 'retrieve' },
  { type: 'quiz', question: '12. Why can\'t RAG guarantee 100% correctness?', options: ['Sources can be wrong, retrieval can miss key content, and the model can still misread', 'RAG never uses source material', 'Any answer with references is always correct'], correct: 0 },
  { type: 'quiz', question: '13. If a model answers based on wrong source material, is the problem always only model hallucination?', options: ['Not always; you must also check source quality', 'Yes, because sources are always correct', 'Yes, and lowering temperature always fixes it'], correct: 0 },
  { type: 'quiz', question: '14. How do you fairly compare direct answering vs RAG answering?', options: ['Use the same question and track factual accuracy, citation alignment, and source quality', 'Ask different questions and only compare which answer is longer', 'Only compare professional tone'], correct: 0 },
  { type: 'practice', task: '15. Three detective helpers: For "What is today\'s temperature in Beijing?" "What is 378×492?" and "Write three openings for a Mars story," choose direct generation, reliable retrieval, or a calculation tool for each, and explain how you would verify each result.', rubric: 'A strong answer uses up-to-date reliable retrieval for weather and checks date/location; uses calculator or code for arithmetic and checks input values; allows direct generation for creative writing but adds human review. It clearly states that different tasks require different evidence and that lowering temperature alone is not enough.', placeholder: 'Weather: method...; verification...\nArithmetic: method...; verification...\nStory: method...; verification...', minLength: 80, referenceAnswer: 'For weather, use an authoritative weather source and verify Beijing, date, and update time. For arithmetic, use a calculator and confirm the input is exactly 378×492. For story openings, direct generation is fine; then I review originality and fit to theme. Different tasks need different evidence.' }
];

export const v3enw1d6Data: DayContent = {
  day: 6,
  title: 'Fluent Is Not Always True: Training, Inference, and Hallucination',
  shards: 1,
  steps: [
    { type: 'theory', content: 'Chapter 1: How models grow. Pretraining is like reading huge amounts of material and practicing continuation to learn language and world patterns. Fine-tuning is like targeted training. Alignment adds behavior rules. These improve ability, but they do not turn a model into a perfectly correct, real-time fact database.' },
    { type: 'video', url: '', content: 'Animation: when pretraining, fine-tuning, alignment, and inference happen' },
    { type: 'theory', content: 'Chapter 2: Inference is not retraining. Each time you send a prompt, the model uses existing parameters and current context to generate tokens step by step. This stage is inference. A normal chat does not make the model run pretraining again on the spot.' },
    { type: 'theory', content: 'Chapter 3: Good continuation can still invent details. The model is trained to produce plausible next text. With weak evidence, it may still invent a fake book, wrong date, or false citation. More fluent wording does not mean stronger evidence.' },
    { type: 'theory', content: 'Chapter 4: Equip the model with tools. Use reliable retrieval for latest facts, controlled RAG for private documents, and calculators or code for exact computation. After tools return results, still check sources, parameters, and citation alignment. Tools are evidence channels, not automatic truth stamps.' },
    ...graded,
    { type: 'theory', content: 'Day 6 complete. You can now distinguish pretraining, fine-tuning, alignment, and inference, and you know hallucination is not fixed by "just asking again." Tomorrow is the Week 1 Boss challenge: rebuild the full chain from token to final output.' }
  ]
};
