import { DayContent } from '../../../types';

export const v3enw1d4Data: DayContent = {
  day: 4,
  title: 'Word Radar: Transformer, Attention, and QKV',
  shards: 1,
  steps: [
    { type: 'theory', content: 'Why are static embeddings not enough? The word "Apple" can mean a fruit or a company. Transformer updates each token using context. Attention works like a radar: the current token asks a question, scans other tokens, decides which ones matter, and absorbs useful information.' },
    { type: 'video', url: '', content: 'Animation: in "Apple released a phone," how "Apple" points its radar at "released" and "phone"' },
    { type: 'quiz', question: '1. Why can\'t static embeddings alone solve polysemy?', options: ['They do not know the specific context around the word in the current sentence', 'They cannot represent numbers', 'A word can appear in only one sentence'], correct: 0 },
    { type: 'quiz', question: '2. Which description best matches attention?', options: ['It dynamically assigns attention weights from the current token to other tokens', 'It automatically searches the internet and verifies facts', 'It permanently stores all words in long-term memory'], correct: 0 },
    { type: 'fill', question: '3. Attention is like turning on a word ___ to find relevant context.', parts: ['Attention is like turning on a', '___', '.'], options: ['radar', 'calculator', 'camera'], correct: 'radar' },
    { type: 'theory', content: 'Q, K, and V are like library search. Query (Q) is what you are looking for now. Key (K) is each book\'s tag for matching. Value (V) is the actual content you retrieve after matching. The model compares Q with many Ks, creates weights, then mixes the related Vs by those weights.' },
    { type: 'match', question: '4. Match QKV with the library analogy.', pairs: [{ left: 'Query', right: 'The topic the reader is currently searching for' }, { left: 'Key', right: 'The label used to match each book' }, { left: 'Value', right: 'The actual content retrieved from the book' }, { left: 'Attention weight', right: 'How important each book is to the current question' }] },
    { type: 'quiz', question: '5. Why does the model compare Q and K?', options: ['To decide which positions are more relevant to the current token', 'To check if the answer is objectively true', 'To count how many tokens exist in the vocabulary'], correct: 0 },
    { type: 'quiz', question: '6. Why is V still needed after Q-K matching?', options: ['V carries the actual information to retrieve and combine', 'V deletes all low-score tokens', 'V is the model version number'], correct: 0 },
    { type: 'theory', content: 'From match scores to percentages. The model computes several matching scores, then uses Softmax to convert them into attention weights that sum to 100%. For example, a token may give 70% to a subject, 20% to an action, and 10% to others. High weight means stronger dependency in computation, not guaranteed truth.' },
    { type: 'quiz', question: '7. If three attention weights are 0.6, 0.3, and 0.1, what is their sum?', options: ['0.1', '1', '3'], correct: 1 },
    { type: 'quiz', question: '8. If one word gets 90% attention weight, does that prove the final answer is true?', options: ['Yes, above 80% means true', 'No, weight shows computational relevance, not fact certification', 'Yes, but only for history questions'], correct: 1 },
    { type: 'fill', question: '9. Softmax converts matching scores into attention ___.', parts: ['Softmax outputs attention', '___', '.'], options: ['weights', 'vocabulary', 'coordinates'], correct: 'weights' },
    { type: 'theory', content: 'Position is like class roll call. If the model receives an unordered bag of words, "cat chases dog" and "dog chases cat" look similar in ingredients. Positional encoding tells the model who comes first and next. Multi-head attention is like several detectives working at once: one tracks grammar, one tracks references, one tracks long-distance links.' },
    { type: 'quiz', question: '10. What does positional encoding mainly help the model know?', options: ['Token order and relative positions in the sequence', 'Whether each fact is correct', 'The user\'s city'], correct: 0 },
    { type: 'quiz', question: '11. Without position info, why is it hard to distinguish "cat chases dog" from "dog chases cat"?', options: ['They contain the same words, but order determines role relations', 'Cat and dog have no embeddings', 'Chinese has no punctuation'], correct: 0 },
    { type: 'quiz', question: '12. What is the intuitive advantage of multi-head attention?', options: ['It can simultaneously focus on grammar, references, and other relationships', 'It automatically calls multiple search engines', 'It guarantees every head gives the same answer'], correct: 0 },
    { type: 'match', question: '13. Match each issue with a likely diagnostic clue.', pairs: [{ left: 'Pronoun points to the wrong entity', right: 'Related token matching or context may be insufficient' }, { left: 'Subject-object role reversal', right: 'Position and word-order information may be misused' }, { left: 'A distant condition is ignored', right: 'Long-range relation did not get enough attention' }, { left: 'Wrong fact is cited', right: 'Attention alone is not enough; external verification is still needed' }] },
    { type: 'quiz', question: '14. In "The trophy does not fit in the suitcase because it is too big," what should the model combine most to resolve "it"?', options: ['The context relations among trophy, suitcase, not fit, and too big', 'The font color of the sentence', 'Randomly pick the nearest word'], correct: 0 },
    { type: 'practice', task: '15. Word Radar Lab: Choose one sentence with a pronoun or ambiguous word. Write what the current token\'s Query is looking for, list two candidate Keys, and explain which Value should be retrieved. Then modify word order or context and predict how attention focus changes.', rubric: 'A strong answer includes a sentence with real ambiguity, a clear query target, at least two candidate matches, a retrieval choice, and a reasonable prediction after context changes. Exact internal model weights are not required.', placeholder: 'Sentence: ...\nQuery target: ...\nCandidate Keys: ...\nChosen Value: ...\nAfter context change: ...', minLength: 70, referenceAnswer: 'Sentence: "Xiaoming gave the book to Xiaogang because he has a speech tomorrow." The query is who "he" refers to; candidate keys are Xiaoming and Xiaogang; the retrieved value comes from action/context clues around the speech. If changed to "Xiaogang took the book, because Xiaogang has a speech tomorrow," attention should point more clearly to Xiaogang.' },
    { type: 'theory', content: 'Day 4 complete. You now know how Transformer uses attention to exchange contextual information: Q asks, K matches, V provides content, and positional encoding preserves order. Tomorrow we will see how the model scores the next token and selects it with temperature and sampling.' }
  ]
};
