import type { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. In Week 3 Boss, what is the only valid final deliverable?', options: ['A text-and-image story', 'A storyboard prototype only', 'A finished 15-30-second knowledge short film', 'A set of unedited generated clips'], correct: 2 },
  { type: 'quiz', question: '2. How should factual claims in your Boss script be handled?', options: ['Each claim can be traced to reliable sources with citation records', 'Let AI auto-complete facts', 'Keep anything that sounds plausible', 'Use disclaimer instead of citation'], correct: 0 },
  { type: 'quiz', question: '3. What does “continuous shots” mean?', options: ['All shots use the same framing', 'Character, props, actions, and story connect across shots', 'Every shot uses the same camera motion', 'Put three unrelated clips together'], correct: 1 },
  { type: 'quiz', question: '4. Which audio element is required in a complete final film?', options: ['Background music only', 'Auto subtitles only', 'Clear narration with synced subtitles', 'Narration text file without recording'], correct: 2 },
  { type: 'quiz', question: '5. When publishing AI-generated visuals, release notes should include...', options: ['Only the project title', 'AI generated/assisted disclosure plus asset usage status', 'Hide the production process', 'Label generated visuals as real filming'], correct: 1 },
  { type: 'quiz', question: '6. For a 20-second final film, what best proves the knowledge is communicated clearly?', options: ['Many transitions', 'Viewers can state the core fact and find its source', 'Popular background music', 'Complex motion in every shot'], correct: 1 },
  { type: 'fill', question: '7. Boss final duration must be between 15 and ___ seconds.', parts: ['Boss final duration must be between 15 and', '___', 'seconds.'], options: ['30', '45', '60'], correct: '30' },
  { type: 'fill', question: '8. Text that appears in sync with narration is called ___.', parts: ['Text appearing in sync with narration is called', '___', '.'], options: ['subtitles', 'script', 'sources'], correct: 'subtitles' },
  { type: 'fill', question: '9. Results for fact, copyright, privacy, and AI disclosure checks must go into the release check ___.', parts: ['These results must be written in the release check', '___', '.'], options: ['record', 'shot', 'prompt'], correct: 'record' },
  { type: 'quiz', question: '10. You have script, key visual, and storyboard, but no exported video. Boss verdict?', options: ['Not qualified. You must finish narration, subtitles, editing, and export a 15-30-second final film', 'Qualified. Script can replace final film', 'Qualified. Key visual counts as the final story', 'Only verbal explanation is needed'], correct: 0 },
  { type: 'practice', task: '11. [Boss Final Delivery Sheet] Write your final delivery record for the 15-30-second knowledge film: title and core fact, script and sources, key visual note, 2-3 continuous shots, narration/subtitle status, final duration and file, plus release check results.', rubric: 'Must explicitly deliver a playable 15-30-second final film. Text-image story, script only, storyboard only, or prototype only are not accepted. Record must fully cover script/sources, key visual, continuous shots, narration/subtitles, final file, and release checks for facts/copyright/privacy/AI labeling.', placeholder: 'Title: ... | Core fact: ... | Source: ...\nKey visual: ...\nContinuous shots: 1. ... 2. ... 3. ...\nNarration/subtitles: ... | Final film: ... sec, file ...\nRelease checks: facts ...; copyright ...; privacy ...; AI labeling ...', minLength: 170, referenceAnswer: 'Title: “Borrowed Moonlight.” Core fact: the Moon does not emit light; it mainly reflects sunlight. Script is based on a public planetarium source with page title, institution, and access date. Key visual shows the dragon observing the Moon and is labeled AI-assisted. Shot 1 raises the question, Shot 2 presents sunlight-to-Moon evidence, Shot 3 concludes with source, with consistent character/props continuity. Narration is clear and subtitles are synced. Exported final MP4 is 22 seconds. Release checks confirm fact traceability, licensed audio/images, no personal privacy leakage, and end-card AI disclosure.' },
  { type: 'match', question: '12. Match: Boss deliverables', pairs: [{ left: 'Script and sources', right: 'Prove knowledge is verifiable' }, { left: 'Key visual and continuous shots', right: 'Build a coherent visual story' }, { left: 'Narration and subtitles', right: 'Make content hearable and readable' }, { left: '15-30-second final film', right: 'Final playable output file' }] },
  { type: 'match', question: '13. Match: continuity checks', pairs: [{ left: 'Backpack color suddenly changes', right: 'Unify character anchors' }, { left: 'Shot 1 shows card in hand, Shot 2 card disappears', right: 'Fix prop continuity' }, { left: 'Character exits right but enters next shot from right', right: 'Correct motion direction' }, { left: 'Story jumps from discovery to conclusion', right: 'Insert verification shot' }] },
  { type: 'match', question: '14. Match: unqualified delivery and fix', pairs: [{ left: 'Only a text-image story', right: 'Add narration/subtitles and edit into video' }, { left: 'Only storyboard prototype', right: 'Complete continuous shots and export final' }, { left: 'Final film is 42 seconds', right: 'Trim to 15-30 seconds' }, { left: 'Video has no source info', right: 'Add source verification record and source end-card' }] },
  { type: 'match', question: '15. Match: release checklist records', pairs: [{ left: 'Fact check', right: 'Map each claim to a reliable source' }, { left: 'Copyright check', right: 'Confirm music, images, and fonts are usable' }, { left: 'Privacy check', right: 'Remove personal data without consent' }, { left: 'AI check', right: 'Label generated or assisted parts clearly' }] },
];

export const v3enw3d7Data: DayContent = {
  day: 7,
  title: 'Boss Dragon on Screen: Final Film + Mechanism Notes + Fix Log + Release Checks',
  shards: 60,
  isBoss: true,
  steps: [
    { type: 'theory', content: '🐉 **Boss Kickoff | Four Required Deliverables**\nToday you must submit: a 15-30-second final film, key mechanism notes (image understanding / image generation / video / audio pipelines), a fix log, and a release checklist. Text-image stories or prototypes do not count as complete.' },
    { type: 'video', url: '', content: 'Video: from reliable script to a finished 15-30-second knowledge short film' },
    { type: 'theory', content: '📚 **Card 1 | Explain Mechanisms Clearly**\nAt minimum, explain: how the visual encoder reads images, how diffusion generates images, how keyframes form video, and how TTS/ASR validate audio.' },
    { type: 'theory', content: '🎬 **Card 2 | Fix Log**\nRecord at least two fixes: symptom, diagnosed cause, parameter/prompt adjustment, and final result. Make your process traceable.' },
    { type: 'theory', content: '✅ **Card 3 | Final Release Gate**\nFinal film, factual sources, licensing, privacy, and AI disclosure must all pass. If any one fails, revise before release.' },
    ...graded,
    { type: 'theory', content: '🏆 **Week 3 Completed**\nYou have combined reliable sources, original key visuals, continuous shots, narration/subtitles, and release responsibility into one 15-30-second knowledge film. Completion is not “AI generated it.” Completion is playable output, traceable facts, usable assets, and clear audience understanding.' },
  ],
};
