import type { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. When turning your script into a key visual, what should come first?', options: ['Extract the most important, visible knowledge moment', 'Put every narration line into one image', 'Pick a trendy style first', 'Fill the image with lots of text'], correct: 0 },
  { type: 'quiz', question: '2. Which set fully covers the five prompt parts for a key visual?', options: ['Title, author, date, link, rating', 'Subject, scene, composition, style, constraints', 'Character, dialogue, music, subtitles, transitions', 'Colors, size, filename, score, version'], correct: 1 },
  { type: 'quiz', question: '3. “The Moon is centered and fills about half the frame; the Sun is upper-right” mainly describes what?', options: ['Subject', 'Knowledge fact', 'Composition', 'Constraint'], correct: 2 },
  { type: 'quiz', question: '4. What is the most important acceptance standard for a knowledge key visual?', options: ['Maximum decorative elements', 'At first glance, the core knowledge relation is clear and fact-consistent', 'Very bright colors only', 'Looks like a popular movie'], correct: 1 },
  { type: 'quiz', question: '5. Generated text appears as gibberish. What is the safer fix?', options: ['Keep it and explain it away', 'Set image to no text and add title in post-editing', 'Add even more text prompts', 'Treat gibberish as a scientific symbol'], correct: 1 },
  { type: 'quiz', question: '6. Prompt says “in the style of a living artist.” Better revision?', options: ['Keep the name and add “original”', 'Switch to another artist name', 'Describe visible style traits instead, such as clean science illustration, paper grain, soft side light', 'Only write “premium feel”'], correct: 2 },
  { type: 'fill', question: '7. The first thing in a prompt is the core ___.', parts: ['The first thing to define is the core', '___', '.'], options: ['subject', 'filename', 'rating'], correct: 'subject' },
  { type: 'fill', question: '8. “Subject centered, leave title space in upper-right” describes ___.', parts: ['This sentence describes', '___', '.'], options: ['composition', 'constraints', 'source'], correct: 'composition' },
  { type: 'fill', question: '9. “No text, no logo, no extra planets” belongs to prompt ___.', parts: ['These belong to prompt', '___', '.'], options: ['constraints', 'scene', 'subject'], correct: 'constraints' },
  { type: 'quiz', question: '10. D1 script says “The Moon reflects sunlight.” Which visual is most accurate?', options: ['The Moon emits light beams by itself', 'Sunlight points to the Moon, with a clearly lit side and clear relation', 'Put many unrelated planets around the Moon'], correct: 1 },
  { type: 'practice', task: '11. [Knowledge Key Visual] Pick one core moment from your D1 15-30-second script. Write a full prompt with subject, scene, composition, style, and constraints. Then generate or plan one image and evaluate it on four checks: knowledge accuracy, clear subject, crop safety, and no extra text/logo.', rubric: 'Prompt must include all five parts and stay consistent with D1 facts. Evaluation must comment on all four checks. The image should work as a key visual without relying on tiny in-image text.', placeholder: 'Core script line: ...\nSubject: ...\nScene: ...\nComposition: ...\nStyle: ...\nConstraints: ...\nEvaluation: knowledge accuracy ...; subject clarity ...; crop safety ...; no extra text/logo ...', minLength: 90, referenceAnswer: 'Core script line: The Moon does not emit light; we see reflected sunlight. Subject: Moon lit by sunlight. Scene: simple deep-space background with distant Sun. Composition: Moon centered at half-frame, Sun upper-right, clear light direction, title-safe area upper-left. Style: clear science illustration for teens, blue-gray lunar texture, soft lighting. Constraints: no text, no logo, no extra planets, Moon must not glow by itself. Evaluation: relation is accurate; subject is clear; works in vertical and horizontal crops; no extra text/logo.' },
  { type: 'match', question: '12. Match: five-part prompt', pairs: [{ left: 'The Moon lit by sunlight', right: 'Subject' }, { left: 'Simple deep-space background', right: 'Scene' }, { left: 'Moon centered, upper-left negative space', right: 'Composition' }, { left: 'Clean science illustration, soft light', right: 'Style' }] },
  { type: 'match', question: '13. Match: script to image', pairs: [{ left: 'Find the single most important sentence', right: 'Set knowledge core' }, { left: 'Turn causal relation into visible elements', right: 'Design visual relation' }, { left: 'Decide what the eye sees first', right: 'Arrange visual hierarchy' }, { left: 'Check against source facts', right: 'Verify factual accuracy' }] },
  { type: 'match', question: '14. Match: common issues and fixes', pairs: [{ left: 'Subject appears too small', right: 'Increase subject proportion and simplify background' }, { left: 'Light direction contradicts the science', right: 'Specify light source and lit side clearly' }, { left: 'Generated text is garbled', right: 'Switch to no text and add typography later' }, { left: 'Background steals attention', right: 'Reduce irrelevant objects and high-contrast details' }] },
  { type: 'match', question: '15. Match: key visual acceptance checks', pairs: [{ left: 'Image relation matches the script', right: 'Knowledge accuracy' }, { left: 'Still clear when thumbnail-sized', right: 'Subject clarity' }, { left: 'Safe area works in both aspect ratios', right: 'Crop readiness' }, { left: 'No gibberish, signature, or brand mark', right: 'Constraint met' }] },
];

export const v3enw3d3Data: DayContent = {
  day: 3,
  title: 'Image Generation Engine: Diffusion, Latent Space, Seed, Steps, CFG',
  shards: 30,
  steps: [
    { type: 'theory', content: '🎨 **Opening | From Noise to Image**\nNow we switch to the “image-making” engine: diffusion denoises step by step in latent space. Today\'s key controls are Seed, Steps, and CFG.' },
    { type: 'video', url: '', content: 'Video placeholder: use a five-part prompt to turn your script into a usable key visual' },
    { type: 'theory', content: '🧱 **Theory Card 1 | Latent Space and Seed**\nSeed is like a random starting index. With the same model and parameters, it tends to reproduce style direction; different seeds create variation in details.' },
    { type: 'theory', content: '🧭 **Theory Card 2 | Steps and CFG**\nSteps control denoising iterations. CFG controls prompt-following strength. Too low may drift off-topic; too high may become rigid and add artifacts.' },
    { type: 'theory', content: '✅ **Theory Card 3 | Parameter Experiment Discipline**\nRun single-variable experiments: hold Seed fixed while changing Steps or CFG, or hold parameters fixed and only change Seed. Otherwise you cannot identify what caused changes.' },
    ...graded,
    { type: 'theory', content: '🏁 **Wrap-up | Key Visual Complete**\nSave your D1 core sentence, five-part prompt, key visual, and four acceptance results. This becomes the visual anchor for tomorrow\'s continuous shots.' },
  ],
};
