import type { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. If the subject changes across continuous shots, what should you add first?', options: ['More unrelated background', 'Stable repeatable visual anchors', 'A longer story title', 'A completely different style per frame'], correct: 1 },
  { type: 'quiz', question: '2. Which group is best as visual anchors?', options: ['Beautiful, mysterious, epic', 'Blue-gray lunar surface, three craters at lower-right, thin white rim light', 'Cinematic, blockbuster, premium', 'Roughly similar to previous frame'], correct: 1 },
  { type: 'quiz', question: '3. Main role of a reference image in continuous shots?', options: ['Prove generated content is always true', 'Help keep subject shape, color, and style close', 'Automatically fix all knowledge errors', 'Replace storyboard and prompt'], correct: 1 },
  { type: 'quiz', question: '4. Why use “change one thing at a time”?', options: ['You can only generate one image each time', 'You can tell which edit caused the result', 'You no longer need to save older versions', 'It guarantees 100% identity consistency'], correct: 1 },
  { type: 'quiz', question: '5. Shot 2 only needs a framing change. How should the prompt be written?', options: ['Change color, scene, subject, and style together', 'Keep all anchors and only change wide shot to close-up', 'Remove reference image and anchors', 'Rewrite an unrelated topic'], correct: 1 },
  { type: 'quiz', question: '6. Subject stays consistent but knowledge relation is wrong in shot 2. What should you do?', options: ['Keep it if it looks good', 'Log the issue and only fix the wrong knowledge relation', 'Change shot 1 to match the mistake', 'Cover the visual error with subtitles'], correct: 1 },
  { type: 'fill', question: '7. Repeated color, shape, and marks across shots are visual ___.', parts: ['These stable features are visual', '___', '.'], options: ['anchors', 'filters', 'transitions'], correct: 'anchors' },
  { type: 'fill', question: '8. To know which edit worked, each version changes one ___.', parts: ['Each version changes one', '___', '.'], options: ['variable', 'folder', 'story'], correct: 'variable' },
  { type: 'fill', question: '9. The table that stores version number, edits, and outcomes is a version ___.', parts: ['This table is a version', '___', '.'], options: ['log', 'cover', 'subtitle'], correct: 'log' },
  { type: 'quiz', question: '10. Which version log is most reproducible?', options: ['Shot 2 looks better', 'V2: changed only wide shot to close-up; anchors unchanged; crater positions stable, lighting slightly cooler', 'Tried again and it felt good'], correct: 1 },
  { type: 'practice', task: '11. [Continuous Shot Experiment] Based on your D3 key visual, produce at least 2 continuous frames for a 15-30-second story. First define 3-5 visual anchors and use your D3 key visual as reference. In Shot 2, change only one variable. Submit shot notes and complete V1/V2 version logs.', rubric: 'Must include at least two continuous frames; list three to five concrete visible anchors; identify the reference image; Shot 2 changes only one variable; version log includes version id, preserved items, single change, result, and next step. Subject, style, and knowledge relation should stay consistent.', placeholder: 'Visual anchors: 1. ... 2. ... 3. ...\nReference image: D3 key visual\nShot 1: ...\nShot 2: ...\nSingle change: ...\nV1 log: preserved ...; result ...\nV2 log: preserved ...; changed ...; result ...; next step ...', minLength: 110, referenceAnswer: 'Visual anchors: blue-gray lunar surface; three craters at lower-right; Sun always upper-right; lit side facing right; clean science-illustration style. Reference image: D3 key visual. Shot 1: wide shot showing sunlight hitting the Moon. Shot 2: close-up of light-shadow boundary. Single change: framing from wide to close-up. V1: all anchors preserved, relation clear. V2: color/craters/light direction/style preserved, only framing changed; subject mostly consistent, craters shifted slightly left; next version only fixes crater position.' },
  { type: 'match', question: '12. Match: consistency materials', pairs: [{ left: 'Blue-gray lunar surface', right: 'Color anchor' }, { left: 'Three craters at lower-right', right: 'Shape and position anchor' }, { left: 'D3 key visual', right: 'Reference image' }, { left: 'Clean science illustration', right: 'Style anchor' }] },
  { type: 'match', question: '13. Match: one-change rule', pairs: [{ left: 'Wide shot to close-up; all else unchanged', right: 'Single variable: framing' }, { left: 'Day scene to night scene; all else unchanged', right: 'Single variable: time mood' }, { left: 'Subject, scene, and style all changed together', right: 'Cannot isolate cause of change' }, { left: 'Keep old prompt and outputs per version', right: 'Easy to compare and roll back' }] },
  { type: 'match', question: '14. Match: drift issues and fixes', pairs: [{ left: 'Subject color turns green', right: 'Reinforce color anchors' }, { left: 'Signature craters disappear', right: 'Strengthen shape and position anchors' }, { left: 'Style suddenly becomes photoreal', right: 'Fix style wording and reference image' }, { left: 'Light source flips to left side', right: 'Restore light direction and science relation' }] },
  { type: 'match', question: '15. Match: version log fields', pairs: [{ left: 'V1, V2', right: 'Version ID' }, { left: 'Color, shape, style unchanged', right: 'Preserved items' }, { left: 'Only changed wide shot to close-up', right: 'Single change' }, { left: 'Crater shifted; next version fixes position', right: 'Result and next step' }] },
];

export const v3enw3d4Data: DayContent = {
  day: 4,
  title: 'Image Control: Positive/Negative Prompts, Reference Images, Local Edits, Version Consistency',
  shards: 30,
  steps: [
    { type: 'theory', content: '🎬 **Opening | Four Tools for Controlled Generation**\nToday we focus on positive prompts, negative prompts, reference images, and local editing (inpaint/outpaint). Goal: change what you need, keep what you do not want to move.' },
    { type: 'video', url: '', content: 'Video placeholder: build continuous shots using visual anchors, reference images, and version logs' },
    { type: 'theory', content: '⚓ **Theory Card 1 | Positive + Negative Prompt Teamwork**\nPositive prompts define what you want. Negative prompts explicitly block artifacts, gibberish text, and wrong style. Together they are more stable than piling up positive words only.' },
    { type: 'theory', content: '🖼️ **Theory Card 2 | Reference Images and Local Editing**\nReference images help lock identity and style. Local edits change only selected regions, avoiding full redraw drift.' },
    { type: 'theory', content: '🔬 **Theory Card 3 | Version Consistency**\nTrack local edit range in V1/V2/V3 logs. Check identity consistency, light direction, and knowledge relation every time.' },
    ...graded,
    { type: 'theory', content: '🏁 **Wrap-up | Continuous Shot Pack Complete**\nYour project box should now include a D3 reference image, 3-5 visual anchors, at least two continuous shot frames, and V1/V2 logs. Together they form a stable visual segment for your knowledge short.' },
  ],
};
