import { DayContent } from '../../../types';

export const v3enw1d3Data: DayContent = {
  day: 3,
  title: 'Semantic Star Map: Embeddings and Vectors',
  shards: 1,
  steps: [
    { type: 'theory', content: 'ID numbers are not meanings. Yesterday, tokenization turned text into IDs, but ID 100 and ID 101 being close does not mean their meanings are close. Embedding converts each token into a list of numbers, a vector. Imagine coordinates on a semantic star map: cat and dog may be close, while cat and engine are usually farther apart.' },
    { type: 'video', url: '', content: 'Animation: placing cat, dog, car, and bicycle on a 2D semantic map' },
    { type: 'quiz', question: '1. If token IDs 100 and 101 are adjacent, does that prove similar meaning?', options: ['Yes, ID distance is semantic distance', 'No, token ID is only a vocabulary index', 'Yes, but only in Chinese'], correct: 1 },
    { type: 'quiz', question: '2. What does embedding mainly turn a token into?', options: ['A vector that can be used in computation', 'A fact that has already been verified', 'A fixed-length Chinese explanation'], correct: 0 },
    { type: 'match', question: '3. Match each item with the best description.', pairs: [{ left: 'Cat and dog', right: 'Animal meanings may be relatively close' }, { left: 'Car and bicycle', right: 'Transport meanings may be relatively close' }, { left: 'Token ID', right: 'A discrete index in the vocabulary' }, { left: 'Embedding', right: 'A continuous vector representation' }] },
    { type: 'theory', content: 'A vector is like a multi-dimensional ability bar. A 2D map is only for teaching intuition. Real embeddings often have many dimensions. One dimension alone is not always human-readable, but together they can represent complex relations. More dimensions may hold more features, but also increase storage and compute cost, and do not automatically guarantee correct understanding.' },
    { type: 'fill', question: '4. In math, the list of numbers in an embedding is called a ___.', parts: ['This list of numbers is called a', '___', '.'], options: ['vector', 'vocabulary', 'probability'], correct: 'vector' },
    { type: 'quiz', question: '5. What does increasing vector dimensions usually imply?', options: ['It may represent more features, but also uses more resources', 'Facts become automatically more accurate', 'Each dimension maps directly to one normal word'], correct: 0 },
    { type: 'quiz', question: '6. Why can\'t a 2D semantic map be treated as the model\'s full internal map?', options: ['Real representations are high-dimensional and more complex', 'The model has no numbers inside', '2D coordinates cannot be drawn on a screen'], correct: 0 },
    { type: 'theory', content: 'Compare direction or distance? You can compare vectors by straight-line distance or by direction. Cosine similarity focuses on whether two arrows point in similar directions: same direction near 1, perpendicular near 0, opposite direction near -1. It is useful for semantic retrieval, but a high score means relevance, not fact certification.' },
    { type: 'quiz', question: '7. If two vectors point almost the same way but have very different lengths, what is likely for cosine similarity?', options: ['It can still be high, because cosine mainly compares direction', 'It must be zero', 'It must be negative'], correct: 0 },
    { type: 'fill', question: '8. Cosine similarity mainly compares vector ___.', parts: ['Cosine similarity mainly compares', '___', '.'], options: ['direction', 'ID numbers', 'character count'], correct: 'direction' },
    { type: 'quiz', question: '9. A semantic search result has similarity 0.92. Can we directly conclude the content is correct?', options: ['Yes, anything above 0.9 is true', 'No, similarity means relevance, so we still need source checking', 'Yes, as long as the document is long'], correct: 1 },
    { type: 'match', question: '10. Match each comparison idea to the right focus.', pairs: [{ left: 'Whether vector directions align', right: 'Cosine similarity focuses more on this' }, { left: 'Straight-line distance between points', right: 'Euclidean distance focuses more on this' }, { left: 'Retrieved related passages', right: 'Still needs reading and verification' }, { left: 'High-dimensional representations', right: 'Can hold more complex features' }] },
    { type: 'theory', content: 'The same word can move in context. In "Apples are tasty" and "Apple released a new phone," the starting token may be the same, but after passing through Transformer layers it absorbs surrounding context and becomes different contextual representations. A static embedding is like a dictionary coordinate; context-processed states are closer to actual sentence meaning.' },
    { type: 'quiz', question: '11. Why does "Apple" need different contextual representations in two sentences?', options: ['Neighboring words signal different meanings: fruit vs company', 'The same word gets random IDs each time', 'Because the second sentence is longer'], correct: 0 },
    { type: 'quiz', question: '12. When searching "indoor rainy-day activities," why can results still be relevant even without exact keyword overlap?', options: ['Embeddings can capture some semantic similarity', 'Models search only by first letters', 'No-keyword content is always more accurate'], correct: 0 },
    { type: 'quiz', question: '13. Which conclusion is the most rigorous?', options: ['Semantic closeness equals factual agreement', 'Vectors can represent relationships, but similarity is not factual proof', 'Higher vector dimension means no hallucinations'], correct: 1 },
    { type: 'match', question: '14. Match each phrase with its context meaning.', pairs: [{ left: 'Upload files to the cloud', right: 'Network storage service' }, { left: 'A cloud is floating in the sky', right: 'Weather phenomenon' }, { left: 'Go to the bank to save money', right: 'Financial institution' }, { left: 'The boat is close to the bank', right: 'River edge' }] },
    { type: 'practice', task: '15. Semantic Star Map Lab: Pick four familiar concepts, place them on a 2D map, and explain which pairs should be closer. Then choose one polysemous word, write two different contexts, and explain why static coordinates alone are not enough.', rubric: 'A strong answer includes four concepts with reasoned relative positions, gives two contexts for one ambiguous word, and clearly states that a 2D map is an intuition tool while context changes representation.', placeholder: 'Four concepts and positions: ...\nClose/far relationships: ...\nAmbiguous word and two contexts: ...\nLimits of static coordinates: ...', minLength: 70, referenceAnswer: 'I place cat near dog, and car near bicycle, with the two groups farther apart because one group is animals and the other is transportation. In "Apple is tasty," Apple means fruit. In "Apple released a phone," Apple means the company. A fixed dictionary coordinate alone cannot fully decide meaning; surrounding words are required.' },
    { type: 'theory', content: 'Day 3 complete. Token IDs become vectors through embeddings, and semantic relations can be understood by distance and direction. Tomorrow each word turns on a radar: attention will search context for what is truly relevant.' }
  ]
};
