import { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. What is the first main processing step after text enters the model pipeline?', options: ['The tokenizer splits text into tokens', 'Softmax directly verifies facts', 'Temperature generates embeddings'], correct: 0 },
  { type: 'quiz', question: '2. Why is embedding needed after token IDs?', options: ['IDs do not carry semantic meaning by themselves, so they must become vectors for computation', 'Embeddings are used for web search', 'Token IDs cannot be stored in computers'], correct: 0 },
  { type: 'quiz', question: '3. What does attention mainly do in the generation chain?', options: ['Dynamically combine relevant token information from context', 'Permanently save user data', 'Guarantee no hallucination in output'], correct: 0 },
  { type: 'match', question: '4. Match each component in the pipeline to its role.', pairs: [{ left: 'Tokenizer', right: 'Split text and map to IDs' }, { left: 'Embedding', right: 'Convert IDs into vector representations' }, { left: 'Attention', right: 'Mix relevant information using context' }, { left: 'Logits', right: 'Produce raw scores for next-token candidates' }] },
  { type: 'fill', question: '5. Logits are converted into a probability distribution that sums to 1 by ___.', parts: ['Logits are converted by', '___', '.'], options: ['Softmax', 'Tokenizer', 'RAG'], correct: 'Softmax' },
  { type: 'quiz', question: '6. In which stage do temperature and top-p mainly operate?', options: ['The candidate-probability and sampling-control stage', 'The text splitting stage', 'The pretraining data collection stage'], correct: 0 },
  { type: 'quiz', question: '7. If the model interprets "bank" as a river bank instead of a financial bank, what should be checked first?', options: ['Whether context is sufficient and whether attention captured clues like money or river', 'Image resolution', 'Output filename'], correct: 0 },
  { type: 'quiz', question: '8. If an answer misses an important early requirement, what might be related?', options: ['Context truncation or poor use of key information', 'Softmax probabilities not summing to 1', 'The model having no tokenizer'], correct: 0 },
  { type: 'match', question: '9. Match each failure pattern with a useful checkpoint.', pairs: [{ left: 'A rare word is split into too many tiny pieces', right: 'Check tokenizer and vocabulary behavior' }, { left: 'Ambiguous word is interpreted wrongly', right: 'Check context and attention focus' }, { left: 'Story endings are too similar every run', right: 'Check temperature and candidate-pool settings' }, { left: 'A citation points to non-existent content', right: 'Add reliable sources and do human verification' }] },
  { type: 'quiz', question: '10. If higher temperature causes rare candidates to appear more often, which part changed?', options: ['Probability distribution and sampling behavior', 'Embedding dimension', 'BPE vocabulary training'], correct: 0 },
  { type: 'quiz', question: '11. If the model gives exactly the same output twice, does that prove factual correctness?', options: ['No. Consistency means stability, but evidence is still required', 'Yes. Consistency is verification', 'Yes, but only at low temperature'], correct: 0 },
  { type: 'fill', question: '12. After selecting one token, the model appends it and continues to the next round. This is called ___ generation.', parts: ['This is called', '___', 'generation.'], options: ['autoregressive', 'retrieval-based', 'one-shot'], correct: 'autoregressive' },
  { type: 'quiz', question: '13. Which pipeline order is correct?', options: ['Text -> Token -> Embedding -> Attention -> Logits -> Softmax -> Sampling', 'Text -> Softmax -> Token -> RAG -> Embedding', 'Text -> Temperature -> Tokenizer -> Training'], correct: 0 },
  { type: 'quiz', question: '14. Which combination is most effective for reducing hallucination risk?', options: ['Provide reliable context, use proper tools, and verify outputs', 'Only set temperature to zero', 'Make the prompt as long as possible'], correct: 0 },
  { type: 'practice', isBoss: true, task: '15. Generation Chain Boss: For the question "Why does the Moon shine?" draw the full path from input text to output: Tokenizer, Embedding, Attention, Logits, Softmax, Sampling. Mark at least three possible failure points and give one check or verification method for each.', rubric: 'A full-score answer uses the correct six-stage order, gives at least three specific failure points tied to those stages, and proposes realistic checks such as adding context, adjusting sampling, and using reliable sources/tools. It must not claim that internal probabilities equal factual proof.', placeholder: 'Pipeline: text -> ... -> output\nFailure 1: ...; check: ...\nFailure 2: ...; check: ...\nFailure 3: ...; check: ...', minLength: 120, referenceAnswer: 'Text is first tokenized into IDs, then embeddings map IDs to vectors. Attention combines context around words like moon and shine. The output layer produces logits, Softmax converts them to probabilities, and sampling selects the next token repeatedly. Failure points include vague prompts (fix by clarifying), wrong attention focus (inspect and rewrite context), and random low-quality sampling choices (adjust settings). Most importantly, factual evidence may still be missing, so check reliable astronomy sources.' }
];

export const v3enw1d7Data: DayContent = {
  day: 7,
  title: 'Boss: Inside a Large Model from Input to Output',
  shards: 1,
  isBoss: true,
  steps: [
    { type: 'theory', content: 'Boss Stage 1: Text enters the factory. Input is first split by the tokenizer into word blocks and mapped to IDs. Embedding then turns IDs into vectors. Splitting decides what basic units the model sees, and vectors place these units in a computable semantic space.' },
    { type: 'video', url: '', content: 'Full animation: follow one token through the model pipeline' },
    { type: 'theory', content: 'Boss Stage 2: Words exchange intelligence. Transformer uses attention so tokens can exchange context. Q asks what to find, K is used for matching, V carries retrievable content, and positional encoding preserves order.' },
    { type: 'theory', content: 'Boss Stage 3: Candidate-token draw. Context states go to output logits, Softmax converts scores to probabilities, temperature changes concentration, top-k/top-p narrows candidates, and sampling picks the next token. Then the loop repeats.' },
    { type: 'theory', content: 'Final Boss Stage: Verify after fluency. This chain optimizes plausible continuation, not automatic objective truth. For latest facts, exact calculations, private rules, or important decisions, connect reliable sources, tools, and human verification at the output end.' },
    ...graded,
    { type: 'theory', content: 'Week 1 cleared. You can now explain the full path: how text becomes tokens, tokens become vectors, attention uses context, logits become probabilities through Softmax and sampling, and why hallucinations happen. Next week we will learn to design reliable prompts with clear tasks, context, examples, and acceptance checks.' }
  ]
};
