import { DayContent } from '../../../types';

const graded: DayContent['steps'] = [
  { type: 'quiz', question: '1. When the model prepares the next token, what are logits most like?', options: ['Raw scores for all candidate tokens', 'A list of already-verified facts', 'The number of characters cut by the tokenizer'], correct: 0 },
  { type: 'quiz', question: '2. What is Softmax mainly used for?', options: ['Convert raw scores into probabilities that sum to 1', 'Automatically delete incorrect facts', 'Translate Chinese into English'], correct: 0 },
  { type: 'fill', question: '3. After Softmax, the probabilities of all candidates add up to ___.', parts: ['The total probability is', '___', '.'], options: ['1', '10', 'the number of candidates'], correct: '1' },
  { type: 'quiz', question: '4. What usually happens to the probability distribution when temperature is lowered?', options: ['Top candidates become more dominant, so the distribution is more concentrated', 'All candidate probabilities become exactly equal', 'The model automatically learns new knowledge'], correct: 0 },
  { type: 'quiz', question: '5. What is most likely when temperature is raised?', options: ['Lower-score candidates get more chances, so output becomes more diverse', 'Output becomes definitely more factual', 'The model stops using Softmax'], correct: 0 },
  { type: 'match', question: '6. Match each task with a suitable risk style.', pairs: [{ left: 'Extract a date from a fixed form', right: 'Lower temperature, prioritize stability' }, { left: 'Brainstorm ten fantasy character ideas', right: 'Slightly higher temperature for diversity' }, { left: 'Calculate an exact budget', right: 'Use a calculator tool, not temperature alone' }, { left: 'Verify historical facts', right: 'Check reliable sources; temperature cannot replace evidence' }] },
  { type: 'quiz', question: '7. How does greedy decoding choose at each step?', options: ['It always chooses the current highest-probability candidate', 'It draws lots evenly from all candidates', 'It searches the web before each choice'], correct: 0 },
  { type: 'quiz', question: '8. What does top-k = 3 mean?', options: ['At each step, select only from the 3 candidate tokens with the highest probabilities', 'At each step, output all 3 top-ranked tokens together', 'Start with the third-ranked token and remove the top two candidates'], correct: 0 },
  { type: 'quiz', question: '9. What is the key difference between top-p and top-k?', options: ['Top-p uses a cumulative-probability threshold, so its candidate count can change; top-k keeps a fixed count', 'Top-p keeps exactly p candidates, while top-k uses a changing cumulative-probability threshold', 'Both always keep a fixed number of candidates; only the parameter names differ'], correct: 0 },
  { type: 'fill', question: '10. The strategy that always picks the current highest-probability candidate is called ___ selection.', parts: ['This is called', '___', 'selection.'], options: ['greedy', 'vector', 'retrieval'], correct: 'greedy' },
  { type: 'quiz', question: '11. If temperature is very low, is a date answer guaranteed to be correct?', options: ['Yes, stable means true', 'Not necessarily. It changes selection distribution, but facts still need verification', 'Yes, if the answer is repeated twice'], correct: 1 },
  { type: 'match', question: '12. Match each tool to its role in generation.', pairs: [{ left: 'Logits', right: 'Raw scores for candidate tokens' }, { left: 'Softmax', right: 'Converts scores to a probability distribution' }, { left: 'Temperature', right: 'Controls concentration or flattening of probabilities' }, { left: 'Top-k / Top-p', right: 'Restricts the candidate pool for sampling' }] },
  { type: 'quiz', question: '13. The same prompt gives different endings on different runs. What is the most reasonable explanation?', options: ['Sampling may pick different reasonable candidates', 'The first run permanently changed the model', 'A longer ending is always more accurate'], correct: 0 },
  { type: 'quiz', question: '14. How do you fairly test the effect of temperature?', options: ['Keep model, prompt, and other settings fixed, and change only temperature', 'Change model, topic, and length at the same time', 'In each group, keep only your favorite result'], correct: 0 },
  { type: 'practice', task: '15. Risk Dial Lab: Suppose "This weekend we go to the park ___" has four candidates: walk 60%, picnic 25%, do homework 10%, fly a spaceship 5%. Predict what is more likely at low temperature and high temperature. Then choose settings for an activity notice and for a fantasy story.', rubric: 'A strong answer explains that low temperature concentrates on high-probability candidates, while high temperature gives lower-probability candidates more chance. It chooses stable settings for an activity notice and more open settings for fantasy writing, and clearly states that neither setting guarantees factual correctness.', placeholder: 'Low temperature: ...\nHigh temperature: ...\nActivity notice: ...\nFantasy story: ...\nFact check note: ...', minLength: 70, referenceAnswer: 'At low temperature, "walk" is most likely again and again. At high temperature, "picnic," "do homework," and even "fly a spaceship" become more likely than before. For an activity notice, I would use lower temperature for stable wording. For a fantasy story, I can raise temperature to increase variety. Temperature only changes selection behavior; it does not prove facts.' }
];

export const v3enw1d5Data: DayContent = {
  day: 5,
  title: 'The Risk Dial: From Logits and Softmax to Sampling',
  shards: 1,
  steps: [
    { type: 'theory', content: 'Chapter 1: Candidate ranking. After attention organizes context, the model gives raw scores to candidate tokens in the vocabulary. These scores are logits. Think of them as a ranking board in a word-chain game. Higher score means stronger preference in this context, not guaranteed factual correctness.' },
    { type: 'video', url: '', content: 'Animation: four candidate tokens move from logits to a probability bar chart' },
    { type: 'theory', content: 'Chapter 2: Softmax turns scores into probabilities. Logits can be positive, zero, or negative, so they are not direct probabilities. Softmax converts them to values between 0 and 1, with total sum equal to 1. For now, treat it as a fair converter; full equations can come later.' },
    { type: 'theory', content: 'Chapter 3: Temperature is a risk dial. Lower temperature makes top candidates stand out more, so output is usually steadier. Higher temperature flattens gaps and gives less likely candidates more chance, so output is more diverse. Temperature does not add knowledge and is not an accuracy switch.' },
    { type: 'theory', content: 'Chapter 4: Shrink the candidate pool first. Top-k keeps a fixed number of top candidates. Top-p accumulates probability from high to low until a threshold, so candidate count changes by context. Greedy always takes rank 1; sampling chooses by probability inside the kept pool.' },
    ...graded,
    { type: 'theory', content: 'Day 5 complete. You can now connect Logits -> Softmax -> Temperature -> Top-k/Top-p -> Sampling. Tomorrow we tackle a deeper question: why can this generation machine sound very fluent yet still be confidently wrong?' }
  ]
};
